In [29]:
using POMDPs, POMDPTools, QuickPOMDPs, MCTS, DiscreteValueIteration, POMDPSimulators, POMDPModels, POMDPPolicies, POMDPModelTools
using Distributions, Combinatorics, StaticArrays, D3Trees, Random
using FileIO, JLD2, TickTock
using NativeSARSOP


## Initialization

In [30]:
global Number_level = 4;
global Action_num = 4;
gamma=0.95

States=Array((1:Number_level))
Observations=Array((1:Number_level))


4-element Vector{Int64}:
 1
 2
 3
 4

In [31]:
Observation_matrix=[
    0.8 0.2 0.0 0.0;
    0.1 0.8 0.1 0.0;
    0.0 0.2 0.8 0.0;
    0.0 0.0 0.0 1.0
]


4×4 Matrix{Float64}:
 0.8  0.2  0.0  0.0
 0.1  0.8  0.1  0.0
 0.0  0.2  0.8  0.0
 0.0  0.0  0.0  1.0

In [32]:
pdf(Categorical(Observation_matrix[1,:]),2)

0.2

In [33]:
Observation_matrix[1,2]

0.2

In [34]:
T=zeros(Number_level,Number_level,3,100);

# Load transition probability matrix for each component
for i in 1:100
    fullname = "C:/Users/hhu98/OneDrive - UW-Madison/POMDP/code/Heterogeneous system/hetero_tm/tm"*string(i);
   
    Transition_matrix = load(fullname*".jld2","transition_matrix");
    # the last term in argument of T, which is written as 'i' here,
    # is the index of component in the heterogeneous system
    T[:,:,1,i].=Transition_matrix; # a=1: do not replace
    T[:,:,2,i].=Transition_matrix; # a=2: corrective replacement
    for j in 1:Number_level
        T[j,:,3,i].=Transition_matrix[1,:]; # a=3: preventive replacement
        end
    # T[Number_level,:,1,i].=Transition_matrix[1,:]
    T[Number_level,:,1,i].=0.0
    T[Number_level,Number_level,1,i]=1.0
    T[Number_level,:,2,i].=Transition_matrix[1,:]

end

In [35]:
# T[:,:,:,30]

In [36]:
NumberUnits=20
limit=12
failure_penalty = -1200.0;
maintenance_penalty = -100.0;
setup_cost = -300.0;
normal_operation = 0.0;
system_penalty=-2000

-2000

In [37]:
Initialstates = zeros(Number_level)
Initialstates[1]=1.0
Initialstates

4-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0

In [38]:
Initialstate = SparseCat(States, Initialstates)

               SparseCat distribution           
     ┌                                        ┐ 
   1 ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 1.0   
   2 ┤ 0.0                                      
   3 ┤ 0.0                                      
   4 ┤ 0.0                                      
     └                                        ┘ 

In [39]:
Initialobs = SparseCat(Observations, Observation_matrix[1,:])

               SparseCat distribution           
     ┌                                        ┐ 
   1 ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 0.8   
   2 ┤■■■■■■■■■ 0.2                             
   3 ┤ 0.0                                      
   4 ┤ 0.0                                      
     └                                        ┘ 

## Define POMDPs

In [40]:
function create_pomdps()

Unit_pomdps = Dict{Int,POMDP}()

for i in 1:NumberUnits

 Unit_pomdps[i]= QuickPOMDP(
    states=States,
    actions=Array((1:Action_num)),
    observations = Observations,
    initialstate = Initialstate,
    initialobs = Initialobs,
    discount = gamma,

    transition = function(s,a)
        if a == 1 # NO REPAIR, NO SYSTEM FAILURE
            return SparseCat(States, T[s,:,1,i])
        end
        if a == 2 # UNIT NOT REPAIRED UNLESS FAILURE BUT REPAIR IN SYSTEM
            if s == Number_level
                s = 1
                return SparseCat(States, T[s,:,2,i])
            else
                return SparseCat(States, T[s,:,2,i])
            end
        end
        if a == 3 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM, NO SYSTEM FAILURE
            if s==Number_level
                s=1
                return SparseCat(States, T[s,:,3,i])
            else
                s = 1
                return SparseCat(States, T[s,:,3,i])
            end
        end
        if a == 4 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM,SYSTEM FAILED
            if s==Number_level
                s=1
                return SparseCat(States, T[s,:,3,i])
            else
                s = 1
                return SparseCat(States, T[s,:,3,i])
            end
        end
    end,

    observation = function(a,s)
        return SparseCat(Observations, Observation_matrix[s,:])
    end,
        
    reward = function (s, a)
        if a == 1 # NO REPAIR, NO SYSTEM FAILURE
            if s == Number_level
                return system_penalty/(limit)
            else
                return normal_operation
            end
        end
        if a == 2 # UNIT NOT REPAIRED UNLESS FAILURE BUT REPAIR IN SYSTEM, NO SYSTEM FAILURE PENALTY
            if s == Number_level
                return failure_penalty +  setup_cost/NumberUnits + normal_operation
            else
                # Here it doesn't matter whether systems fails or not, since C_b does not apply to functional units
                return normal_operation +  setup_cost/NumberUnits
            end
        end
        if a == 3 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM, NO SYSTEM FAILURE PENALTY
            if s==Number_level
                return failure_penalty +  setup_cost/NumberUnits + normal_operation
            else
                # Here it doesn't matter whether systems fails or not, since C_b does not apply to functional units
                return maintenance_penalty +  setup_cost/NumberUnits+ normal_operation 
            end
        end
        if a == 4 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM,SYSTEM FAILED
            if s==Number_level
                return failure_penalty +  setup_cost/NumberUnits + normal_operation + system_penalty/(limit)
            else
                return maintenance_penalty +  setup_cost/NumberUnits + normal_operation
            end
        end
    end,
    
)
end
return Unit_pomdps
end

create_pomdps (generic function with 1 method)

## Solve POMDPs

In [41]:
function solve_pomdps(pomdps)
    policies = Dict{Int, Any}()
    
    for (idx, pomdp) in pomdps
        solver = SARSOPSolver()
        policies[idx] = solve(solver, pomdp)
    end
    
    return policies
end

solve_pomdps (generic function with 1 method)

In [42]:
Unit_pomdps = create_pomdps()

Dict{Int64, POMDP} with 20 entries:
  5  => QuickPOMDP{UUID("f5c2a699-e725-4e8f-b252-adbcb81d2cd7"), Int64, Int64, …
  16 => QuickPOMDP{UUID("e317cb13-40c0-4a43-8da3-af6783205611"), Int64, Int64, …
  20 => QuickPOMDP{UUID("dab042e0-f58d-4241-a6e9-1b8b0d94cb07"), Int64, Int64, …
  12 => QuickPOMDP{UUID("be62d620-32db-422c-abd2-6eb238c8e9fa"), Int64, Int64, …
  8  => QuickPOMDP{UUID("51f30ebe-7915-4848-9c5f-7838fec66cdb"), Int64, Int64, …
  17 => QuickPOMDP{UUID("34b32356-48c6-424f-975d-521b13de1acd"), Int64, Int64, …
  1  => QuickPOMDP{UUID("b427c234-47a3-4735-96bb-47c4694b9213"), Int64, Int64, …
  19 => QuickPOMDP{UUID("08fca380-034a-497b-b39d-3698314c8d51"), Int64, Int64, …
  6  => QuickPOMDP{UUID("d812378d-f570-4763-9f8b-dc104c092b52"), Int64, Int64, …
  11 => QuickPOMDP{UUID("1fbcd60b-bc2a-4b33-aca4-a789aa737560"), Int64, Int64, …
  9  => QuickPOMDP{UUID("77f21481-ec52-4ac5-8c1d-658e08cb40a6"), Int64, Int64, …
  14 => QuickPOMDP{UUID("adf7883d-b88b-413b-98f9-c1b15c62ea1d"), Int64, I

In [43]:
transition(Unit_pomdps[1],1,1)

               SparseCat distribution           
     ┌                                        ┐ 
   1 ┤■■■■■■■■■■■■■■■■■■■■■ 0.846701689363337   
   2 ┤■■■■ 0.153298310636663                    
   3 ┤ 0.0                                      
   4 ┤ 0.0                                      
     └                                        ┘ 

In [44]:
pdf(transition(Unit_pomdps[1],1,1),1), pdf(transition(Unit_pomdps[1],1,1),2)


(0.846701689363337, 0.153298310636663)

In [45]:
T[1,1,1,1], T[1,2,1,1]

(0.846701689363337, 0.153298310636663)

In [46]:
solver = SARSOPSolver()
policy = solve(solver, Unit_pomdps[1])
# Calling observation

AlphaVectorPolicy{QuickPOMDP{Base.UUID("b427c234-47a3-4735-96bb-47c4694b9213"), Int64, Int64, Int64, @NamedTuple{stateindex::Dict{Int64, Int64}, isterminal::Bool, obsindex::Dict{Int64, Int64}, states::Vector{Int64}, observations::Vector{Int64}, discount::Float64, initialobs::SparseCat{Vector{Int64}, Vector{Float64}}, actions::Vector{Int64}, observation::var"#17#20", actionindex::Dict{Int64, Int64}, initialstate::SparseCat{Vector{Int64}, Vector{Float64}}, transition::var"#16#19"{Int64}, reward::var"#18#21"}}, Int64}(QuickPOMDP{Base.UUID("b427c234-47a3-4735-96bb-47c4694b9213"), Int64, Int64, Int64, @NamedTuple{stateindex::Dict{Int64, Int64}, isterminal::Bool, obsindex::Dict{Int64, Int64}, states::Vector{Int64}, observations::Vector{Int64}, discount::Float64, initialobs::SparseCat{Vector{Int64}, Vector{Float64}}, actions::Vector{Int64}, observation::var"#17#20", actionindex::Dict{Int64, Int64}, initialstate::SparseCat{Vector{Int64}, Vector{Float64}}, transition::var"#16#19"{Int64}, reward

In [47]:
policies = Dict()

Dict{Any, Any}()

In [48]:
policies[1] = policy

AlphaVectorPolicy{QuickPOMDP{Base.UUID("b427c234-47a3-4735-96bb-47c4694b9213"), Int64, Int64, Int64, @NamedTuple{stateindex::Dict{Int64, Int64}, isterminal::Bool, obsindex::Dict{Int64, Int64}, states::Vector{Int64}, observations::Vector{Int64}, discount::Float64, initialobs::SparseCat{Vector{Int64}, Vector{Float64}}, actions::Vector{Int64}, observation::var"#17#20", actionindex::Dict{Int64, Int64}, initialstate::SparseCat{Vector{Int64}, Vector{Float64}}, transition::var"#16#19"{Int64}, reward::var"#18#21"}}, Int64}(QuickPOMDP{Base.UUID("b427c234-47a3-4735-96bb-47c4694b9213"), Int64, Int64, Int64, @NamedTuple{stateindex::Dict{Int64, Int64}, isterminal::Bool, obsindex::Dict{Int64, Int64}, states::Vector{Int64}, observations::Vector{Int64}, discount::Float64, initialobs::SparseCat{Vector{Int64}, Vector{Float64}}, actions::Vector{Int64}, observation::var"#17#20", actionindex::Dict{Int64, Int64}, initialstate::SparseCat{Vector{Int64}, Vector{Float64}}, transition::var"#16#19"{Int64}, reward

In [49]:
policy1 = policies[1]
b = [0.1,0.1,0.8,0.0]
value(policy1,b)

-533.5709685134977

In [50]:
function generative(s,a,i,rng=23) # calculate TRUE COMPONENT-LEVEL reward r_i(s_i,a_i) and get evolving states
    if a==1 # No maintenance in the system, no system failure
        crd=Categorical(T[s,:,1,i])
        s=rand(crd)
        r=normal_operation
        obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
        obs = rand(obs_distribution)
        return (sp=s,r=r,o=obs)
    end

    if a==2 # Maintenance occurs in the system, no system failure, corrective maintenance for the unit
        if s==Number_level
            crd=Categorical(T[1,:,2,i])
            s=rand(crd)
            r=failure_penalty  + normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        else
            crd = Categorical(T[s,:,2,i])
            s = rand(crd)
            r = normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        end
    end

    if a==3 # Maintenance occurs in the system, no system failure, preventive maintenance for the unit
        if s==Number_level
            crd=Categorical(T[1,:,3,i])
            s=rand(crd)
            r=failure_penalty  + normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        else
            crd = Categorical(T[s,:,3,i])
            s = rand(crd)
            r = maintenance_penalty+normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        end
    end

    if a==4 # maintenance in system, system failure occurs, preventive replacement for the unit
        if s==Number_level
            crd = Categorical(T[1,:,3,i])
            s = rand(crd)
            r=failure_penalty+ normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        else
            r = maintenance_penalty+normal_operation
            crd = Categorical(T[1,:,3,i])
            s = rand(crd)
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        end
    end
end

        
        
    

generative (generic function with 2 methods)

#### Belief updater

$$b'(s_j)=P(s_j\vert o,a,b)=\dfrac{P(o\vert s_j,a)\sum_{s_i\in \mathcal{S}}P(s_j\vert s_i,a)b(s_i)}{\sum_{s_j\in \mathcal{S}}P(o\vert s_j,a)\sum_{s_i\in \mathcal{S}}P(s_j\vert s_i,a)b(s_i)}$$

In [51]:
# Input: prior belief, action, observation, index of the component
# Output: updated belief of the component
function update_belief(b,a,o,i) 
    # NOTE: 
    # in input, b is belief from last epoch (before a)
    # a is the last action we took
    # o is the new observation after a
    pomdp = Unit_pomdps[i]
    updated_belief = zeros(length(b))
    if o==4
        updated_belief[Number_level]=1.0
        return updated_belief
    end

    if (a==3) ||(a==4)
    # We assume perfect maintenance and it is know to decision maker(belief updater)
        for sp in 1: Number_level
            p_obs = Observation_matrix[sp,o]
            p_trans = pdf(transition(pomdp,1,1),sp) 
            updated_belief[sp] = p_obs * p_trans
        end
        updated_belief ./= sum(updated_belief)
        return updated_belief
    end
    
    for sp in 1:length(states(pomdp)) 
        # p_observation = POMDPs.observation(pomdp,a,sp) 
        # p_obs = pdf(p_observation,o)
        p_obs = Observation_matrix[sp,o]
        p_trans = 0.0
        for s in 1:length(states(pomdp))
            #trans = transition(pomdp, s,a)
            #p_trans += pdf(transition(pomdp, s,a),sp) * pdf(b, s)
            # p_trans += T[s,sp,a] * pdf(b, s)
            # p_trans += T[s,sp,a,i] * b[s]
            p_trans += pdf(transition(pomdp,s,a),sp) * b[s]
        end
        updated_belief[sp] = p_obs * p_trans
    end
        # Normalize the updated belief state to ensure it sums up to 1
        updated_belief ./= sum(updated_belief)
    return updated_belief
end


update_belief (generic function with 1 method)

### System-level decision making

In [52]:
function decision(o, b)
# initialize system-level action vector
    Q=Qfnc(b) # Q is an N*A matrix for each unit-action pair
    a_final = repeat(1:1,NumberUnits)
    failed_components = 0
    for i in 1:NumberUnits # numerate over units
        if o[i]==Number_level # failure state is self-announcing
            failed_components+=1
        end
    end
    if failed_components >= limit # System fails
        for i in 1:NumberUnits
            if o[i]==Number_level
                a_final[i]=4
            else
                a_final[i]=argmax(a->Q[i,a],[2,3]) # If the unit does not fail, the case is the same as a=2,3
            end
        end
        return a_final
    end

    # Based on belief, compare the expected total rewards of setting up maintenance or not
    D0=0.0
    a0=repeat(1:1,NumberUnits)
    for i in 1:NumberUnits
        D0+=Q[i,1]
    end

    D1=0.0
    a1=repeat(1:1,NumberUnits)
    for i in 1:NumberUnits
        a1[i]=argmax(a->Q[i,a],[2,3])
        if o[i]==Number_level
            a1[i]=3
        end
        D1+=Q[i,a1[i]]
    end

    if !(3 in a1)
        return a0
    end

    if D0 > D1
        return a0
    else
        return a1
    end
end


    
    
    


decision (generic function with 1 method)

# $Q$-function
After obtaining $V^*(b)$ from policy, we calculate optimal $Q$-function by
$$Q^*(b,a)=R(b,a)+\gamma  \sum_{o'\in \mathcal{O}} \eta(o'|b,a)V^*(b')$$
where expected immediate reward of taking action $a$ in belief state $b$ is $$R(b,a)=\sum_{s\in \mathcal{S}}R(s,a) b(s),$$
and prior probability of observing $o'$ after taking action $a$ is $$\eta(o'|b,a)=\sum_{s'\in\mathcal{S}} P(o'|s',a)\sum_{s\in\mathcal{S}}T(s'|s,a)b(s)$$

Now $Q$ needs to be specified to each policy for each unit

In [53]:
function Qfnc(b)
    epsilon = 1e-4
    Q=zeros((NumberUnits,4)) 
    # NOTE: Q is defined for each unit (according to their beliefs), not state
    for i in 1:NumberUnits
        # Given unit index, specify the belief state, pomdp model, and policy for it
        belief=b[i]
        pomdp = Unit_pomdps[i]
        policy = Unit_policies[i]

        for a in 1:4
   
            Q_value=0
            for s in 1:Number_level
                Q_value+=belief[s] * POMDPs.reward(pomdp,s,a)
            end
            for o in 1:Number_level
            # the o here is the observation we expect to obtain at next time step, 
            # i.e., after taking the action we are deciding
            # so we don't need input current o
                o_prior = 0 
                for sp in 1:Number_level
                    p_sp=0
                    for s in 1:Number_level
                        p_sp+=pdf(transition(pomdp,s,a),sp) * belief[s]
                    end
                    p_sp=p_sp * Observation_matrix[sp,o]
                    o_prior+=p_sp
                end
     
                bp=update_belief(belief,a,o,i)
      
                if o_prior > epsilon
                    Q_value += gamma * o_prior * value(policy,bp)
                end
            end
            Q[i,a]=Q_value
        end
    end
    return Q
end
        
                
                

Qfnc (generic function with 1 method)

### Iteration

In [ ]:
using DataFrames
df= DataFrame(u=[],K=[],n=[],s=[],m=[],f=[],p=[],lamb=[],mean=[],std=[])

cost=[ 
    [0	-800	-100	-1200 -2000],
    [0	-1200	-100	-1200 -2000],
    [0	-1600	-100	-1200 -2000],
    [0	-2000	-100	-1200 -2000],
    [0  -2400   -100    -1200 -2000],
    [0  -2800   -100    -1200 -2000],
    [0  -3200   -100    -1200 -2000]
] 

for units in [20, 25, 30, 40, 50, 60]

    for K in 2:2:convert(Int64, floor((units+1)/2))  
        
    global NumberUnits=convert(Int64,units)
    global limit=convert(Int64,K)
    #for lambda in [1,0.9,0.75,0.5,0.1,0.075,0.05,0.01,0.0075,0.005,0.0001]
    for lambda in 1:1:1
    global lamb=lambda
    for c in cost
        tick()
        println(units)  
        print("K : ")
        println(K)
        global normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty=c
        println(c)  
        global NumberUnits=units
# POMDPs are defined
global Unit_pomdps = create_pomdps()
# CONTINUE to solve it and store the polices
global Unit_policies = solve_pomdps(Unit_pomdps)
# policy = solve(solver, multiunit)

trials=10000;
simsteps = 100;
results=zeros(trials)*0.1
Threads.@threads  for h in 1:trials
    s=repeat(1:1,NumberUnits)
    o = rand(Initialobs, NumberUnits)
    belief = [Observation_matrix[1,:] for j in 1:NumberUnits]
    R_sequence=[] 
    r=repeat(1:1,NumberUnits)*1.0

    # iteration
    for k in 1:simsteps
        a=decision(o,belief) # system-level decision making: action vector
        
        # SANITY CHECK
        # Update belief for each component individually
        # b=update_belief(b, a, o, multiunit) # what is the sequence of observing, updating belief, taking action?
        
        R_instant = 0.0
        global failed_components=0
        # When generating new state and new reward, we use true states
        for i in 1:NumberUnits # numerate over units
            if o[i]==Number_level # failure state is self-announcing
                failed_components+=1
            end
            s[i],r[i],o[i]=generative(s[i],a[i],i,234) #call generative function for underlying states
            # it might be better to use generative function to give o as well
            #o[i]=emission(s[i]) # observation generated by new underlying state
            belief[i]=update_belief(belief[i], a[i], o[i], i)
            # sum up single-component cost
            R_instant += r[i]
        end
        # add setup cost
        if (2 in a) ||(3 in a) ||(4 in a)
            R_instant += setup_cost
        end
        # add system failure penalty
        if failed_components >= limit
            R_instant += system_penalty
        end
        # record instant reward of current time step
        append!(R_sequence, R_instant)
    end
    R_discounted=0
    for k in 1:simsteps
        R_discounted=gamma * R_discounted+R_sequence[simsteps-k+1]
    end
    results[h]=R_discounted
end # end the 10000 trials

println(units)
            print("k : ")
            println(limit)
println(lambda)

println(mean(results))

println(std(results))
pushfirst!(df,[units,limit,normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty,lamb,mean(results),std(results)])
        
tock()

                    
                    
    end
    end        
end
end


20
K : 2
[0 -800 -100 -1200 -2000]


[ Info:  started timer at: 2025-03-08T14:23:23.150


20
k : 2
1
-21334.15356568197
2520.3332869499923
20
K : 2
[0 -1200 -100 -1200 -2000]


[ Info:         1854.3261379s: 30 minutes, 54 seconds, 326 milliseconds
[ Info:  started timer at: 2025-03-08T14:54:17.513


20
k : 2
1
-25225.667811798055
2797.3431896526217
20
K : 2
[0 -1600 -100 -1200 -2000]


[ Info:         2013.2268396s: 33 minutes, 33 seconds, 226 milliseconds
[ Info:  started timer at: 2025-03-08T15:27:50.781


20
k : 2
1
-28523.610658067322
3095.0182401417705
20
K : 2
[0 -2000 -100 -1200 -2000]


[ Info:         2086.8652329s: 34 minutes, 46 seconds, 865 milliseconds
[ Info:  started timer at: 2025-03-08T16:02:37.687


20
k : 2
1
-31906.553061697436
3307.486123420375
20
K : 2
[0 -2400 -100 -1200 -2000]


[ Info:         2095.4532241s: 34 minutes, 55 seconds, 453 milliseconds
[ Info:  started timer at: 2025-03-08T16:37:33.179


20
k : 2
1
-34547.2849669973
3524.2870382447622
20
K : 2
[0 -2800 -100 -1200 -2000]


[ Info:         1851.9938638s: 30 minutes, 51 seconds, 993 milliseconds
[ Info:  started timer at: 2025-03-08T17:08:25.196


20
k : 2
1
-37471.916920772805
3693.6638055057647
20
K : 2
[0 -3200 -100 -1200 -2000]


[ Info:         1873.3648633s: 31 minutes, 13 seconds, 364 milliseconds
[ Info:  started timer at: 2025-03-08T17:39:38.603


20
k : 2
1
-40237.500308837014
3836.500815548523
20
K : 4
[0 -800 -100 -1200 -2000]


[ Info:         1871.2294421s: 31 minutes, 11 seconds, 229 milliseconds
[ Info:  started timer at: 2025-03-08T18:10:49.899


20
k : 4
1
-18654.553640285478
1777.2234936108086
20
K : 4
[0 -1200 -100 -1200 -2000]


[ Info:         1872.1241472s: 31 minutes, 12 seconds, 124 milliseconds
[ Info:  started timer at: 2025-03-08T18:42:02.053


20
k : 4
1
-21431.987887114043
2021.544664093603
20
K : 4
[0 -1600 -100 -1200 -2000]


[ Info:         1868.7786279s: 31 minutes, 8 seconds, 778 milliseconds
[ Info:  started timer at: 2025-03-08T19:13:10.873


20
k : 4
1
-23930.496779551297
2265.8001274617664
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:         1863.0413999s: 31 minutes, 3 seconds, 41 milliseconds
[ Info:  started timer at: 2025-03-08T19:44:13.951


20
k : 4
1
-26482.74016539944
2491.1608316504844
20
K : 4
[0 -2400 -100 -1200 -2000]


[ Info:         1876.7980948s: 31 minutes, 16 seconds, 798 milliseconds
[ Info:  started timer at: 2025-03-08T20:15:30.778


20
k : 4
1
-28761.96985635249
2709.5389726425924
20
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:          1859.064246s: 30 minutes, 59 seconds, 64 milliseconds
[ Info:  started timer at: 2025-03-08T20:46:29.889


20
k : 4
1
-31230.648470380096
2955.308735114746
20
K : 4
[0 -3200 -100 -1200 -2000]


[ Info:         1872.3952067s: 31 minutes, 12 seconds, 395 milliseconds
[ Info:  started timer at: 2025-03-08T21:17:42.316


20
k : 4
1
-33643.31295089817
3185.054931918126
20

[ Info:         1880.1460619s: 31 minutes, 20 seconds, 146 milliseconds
[ Info:  started timer at: 2025-03-08T21:49:02.504



K : 6
[0 -800 -100 -1200 -2000]
20
k : 6
1
-18328.989141711958
1730.5646910587966
20
K : 6
[0 -1200 -100 -1200 -2000]


[ Info:         1866.4104084s: 31 minutes, 6 seconds, 410 milliseconds
[ Info:  started timer at: 2025-03-08T22:20:08.951


20
k : 6
1
-20867.86035881905
1894.1383523626919
20
K : 6
[0 -1600 -100 -1200 -2000]


[ Info:         1866.8342045s: 31 minutes, 6 seconds, 834 milliseconds
[ Info:  started timer at: 2025-03-08T22:51:15.823


20
k : 6
1
-23045.291762123936
2013.1433131435351
20
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:         1881.6173296s: 31 minutes, 21 seconds, 617 milliseconds
[ Info:  started timer at: 2025-03-08T23:22:37.471


20
k : 6
1
-25172.5372897172
2196.0742937945147
20
K : 6
[0 -2400 -100 -1200 -2000]


[ Info:         1889.3522255s: 31 minutes, 29 seconds, 352 milliseconds
[ Info:  started timer at: 2025-03-08T23:54:06.865


20
k : 6
1
-27066.227573510634
2366.225917273334
20
K : 6
[0 -2800 -100 -1200 -2000]


[ Info:         1883.9673592s: 31 minutes, 23 seconds, 967 milliseconds
[ Info:  started timer at: 2025-03-09T00:25:30.864


20
k : 6
1
-29032.96386728265
2550.9167041584165
20
K : 6
[0 -3200 -100 -1200 -2000]


[ Info:         1881.3305506s: 31 minutes, 21 seconds, 330 milliseconds
[ Info:  started timer at: 2025-03-09T00:56:52.230


20
k : 6
1
-30981.081674172212
2799.303912521521
20
K : 8
[0 -800 -100 -1200 -2000]


[ Info:         1887.9253116s: 31 minutes, 27 seconds, 925 milliseconds
[ Info:  started timer at: 2025-03-09T01:28:20.204


20
k : 8
1
-18217.651477658295
1699.0816079712476
20
K : 8
[0 -1200 -100 -1200 -2000]


[ Info:         1895.9470442s: 31 minutes, 35 seconds, 947 milliseconds
[ Info:  started timer at: 2025-03-09T01:59:56.190


20
k : 8
1
-20673.310485710503
1829.209111389637
20
K : 8
[0 -1600 -100 -1200 -2000]


[ Info:         1888.6231426s: 31 minutes, 28 seconds, 623 milliseconds
[ Info:  started timer at: 2025-03-09T03:31:24.839


20
k : 8
1
-22759.343012639718
1968.8066999638436
20
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:          1877.763091s: 31 minutes, 17 seconds, 763 milliseconds
[ Info:  started timer at: 2025-03-09T04:02:42.641


20
k : 8
1
-24691.599170667712
2103.2543378408927
20

[ Info:         1632.5424761s: 27 minutes, 12 seconds, 542 milliseconds
[ Info:  started timer at: 2025-03-09T04:29:55.214



K : 8
[0 -2400 -100 -1200 -2000]
20
k : 8
1
-26293.866959617455
2252.700341442588
20
K : 8
[0 -2800 -100 -1200 -2000]


[ Info:         1561.4482395s: 26 minutes, 1 second, 448 milliseconds
[ Info:  started timer at: 2025-03-09T04:55:56.706


20
k : 8
1
-28063.346839431186
2414.956157061746
20
K : 8
[0 -3200 -100 -1200 -2000]


[ Info:          1563.863554s: 26 minutes, 3 seconds, 863 milliseconds
[ Info:  started timer at: 2025-03-09T05:22:00.595


20
k : 8
1
-29728.91424810087
2599.058042966273
20
K : 10
[0 -800 -100 -1200 -2000]


[ Info:         1562.4539839s: 26 minutes, 2 seconds, 453 milliseconds
[ Info:  started timer at: 2025-03-09T05:48:03.092


20
k : 10
1
-18139.212175738652
1668.6219336516892
20
K : 10
[0 -1200 -100 -1200 -2000]


[ Info:         1564.2334221s: 26 minutes, 4 seconds, 233 milliseconds
[ Info:  started timer at: 2025-03-09T06:14:07.360


20
k : 10
1
-20552.490591508547
1828.2054379172562
20
K : 10
[0 -1600 -100 -1200 -2000]


[ Info:         1562.6652961s: 26 minutes, 2 seconds, 665 milliseconds
[ Info:  started timer at: 2025-03-09T06:40:10.053


20
k : 10
1
-22600.886794028906
1969.9719562502187
20
K : 10
[0 -2000 -100 -1200 -2000]


[ Info:         1562.5472074s: 26 minutes, 2 seconds, 547 milliseconds
[ Info:  started timer at: 2025-03-09T07:06:12.639


20
k : 10
1
-24468.325316463495
2062.786191332073


[ Info:          1562.499022s: 26 minutes, 2 seconds, 499 milliseconds


20
K : 10
[0 -2400 -100 -1200 -2000]


[ Info:  started timer at: 2025-03-09T07:32:15.186


20
k : 10
1
-25991.726460282338
2188.239992282864
20
K : 10
[0 -2800 -100 -1200 -2000]


[ Info:         1559.9811859s: 25 minutes, 59 seconds, 981 milliseconds
[ Info:  started timer at: 2025-03-09T07:58:15.187


20
k : 10
1
-27444.73241554506
2301.9053247526394
20
K : 10
[0 -3200 -100 -1200 -2000]


[ Info:         1569.5548328s: 26 minutes, 9 seconds, 554 milliseconds
[ Info:  started timer at: 2025-03-09T08:24:24.776


20
k : 10
1
-28825.051564034402
2500.1969807367504
25
K : 2
[0 -800 -100 -1200 -2000]


[ Info:         1570.7871171s: 26 minutes, 10 seconds, 787 milliseconds
[ Info:  started timer at: 2025-03-09T08:50:35.605


25
k : 2
1
-26255.25430101282
2800.6739282000303
25
K : 2
[0 -1200 -100 -1200 -2000]


[ Info:         1926.9085259s: 32 minutes, 6 seconds, 908 milliseconds
[ Info:  started timer at: 2025-03-09T09:22:42.558


25
k : 2
1
-31029.90276005692
3215.6074065343037
25
K : 2
[0 -1600 -100 -1200 -2000]


[ Info:         1904.5475632s: 31 minutes, 44 seconds, 547 milliseconds
[ Info:  started timer at: 2025-03-09T09:54:27.137


25
k : 2
1
-34811.90287853063
3485.282467783675
25
K : 2
[0 -2000 -100 -1200 -2000]


[ Info:         1910.1162702s: 31 minutes, 50 seconds, 116 milliseconds
[ Info:  started timer at: 2025-03-09T10:26:17.302


25
k : 2
1
-38121.29724037123
3647.096884723941
25
K : 2
[0 -2400 -100 -1200 -2000]


[ Info:         1917.9932443s: 31 minutes, 57 seconds, 993 milliseconds
[ Info:  started timer at: 2025-03-09T10:58:15.335


25
k : 2
1
-41556.48124747733
3867.730656222717
25
K : 2
[0 -2800 -100 -1200 -2000]


[ Info:         1912.3021797s: 31 minutes, 52 seconds, 302 milliseconds
[ Info:  started timer at: 2025-03-09T11:30:07.669


25
k : 2
1
-44477.82059097409
3993.298451246269
25
K : 2
[0 -3200 -100 -1200 -2000]


[ Info:         1925.5015658s: 32 minutes, 5 seconds, 501 milliseconds
[ Info:  started timer at: 2025-03-09T12:02:13.219


25
k : 2
1
-47464.609242938015
4154.403600361054
25
K : 4
[0 -800 -100 -1200 -2000]


[ Info:         1925.6343175s: 32 minutes, 5 seconds, 634 milliseconds
[ Info:  started timer at: 2025-03-09T12:34:18.884


25
k : 4
1
-23103.398058670657
1932.4604953136563


[ Info:         1930.5229822s: 32 minutes, 10 seconds, 522 milliseconds
[ Info:  started timer at: 2025-03-09T13:06:29.454


25
K : 4
[0 -1200 -100 -1200 -2000]
25
k : 4
1
-26557.082614493
2211.1297978979414
25
K : 4
[0 -1600 -100 -1200 -2000]


[ Info:         1921.3938289s: 32 minutes, 1 second, 393 milliseconds
[ Info:  started timer at: 2025-03-09T13:38:30.880


25
k : 4
1
-29507.0248912146
2481.7275539849475
25
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:         1928.8451867s: 32 minutes, 8 seconds, 845 milliseconds
[ Info:  started timer at: 2025-03-09T14:10:39.778


25
k : 4
1
-32270.204674967634
2714.4816904959093
25
K : 4
[0 -2400 -100 -1200 -2000]


[ Info:         1937.8252953s: 32 minutes, 17 seconds, 825 milliseconds
[ Info:  started timer at: 2025-03-09T14:42:57.633


25
k : 4
1
-34966.82602163563
2978.0779473687085
25
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:         1922.5852993s: 32 minutes, 2 seconds, 585 milliseconds
[ Info:  started timer at: 2025-03-09T15:15:00.263


25
k : 4
1
-37564.2952748824
3209.370562436325
25
K : 4
[0 -3200 -100 -1200 -2000]


[ Info:         1932.7195284s: 32 minutes, 12 seconds, 719 milliseconds
[ Info:  started timer at: 2025-03-09T15:47:13.031


25
k : 4
1
-40272.04997840111
3408.902514580918
25
K : 6
[0 -800 -100 -1200 -2000]


[ Info:         1937.6545986s: 32 minutes, 17 seconds, 654 milliseconds
[ Info:  started timer at: 2025-03-09T16:19:30.722


25
k : 6
1
-22800.638597920286
1833.0824219562408
25
K : 6
[0 -1200 -100 -1200 -2000]


[ Info:         1938.3030178s: 32 minutes, 18 seconds, 303 milliseconds
[ Info:  started timer at: 2025-03-09T16:51:49.066


25
k : 6
1
-25935.92855156865
2033.0927266249034
25
K : 6
[0 -1600 -100 -1200 -2000]


[ Info:         1932.4782688s: 32 minutes, 12 seconds, 478 milliseconds
[ Info:  started timer at: 2025-03-09T17:24:01.580


25
k : 6
1
-28434.1425623275
2182.1138617526767
25
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:         1934.5319852s: 32 minutes, 14 seconds, 531 milliseconds
[ Info:  started timer at: 2025-03-09T17:56:16.152


25
k : 6
1
-30770.663159861433
2349.9965232604095
25
K : 6
[0 -2400 -100 -1200 -2000]


[ Info:          1943.288279s: 32 minutes, 23 seconds, 288 milliseconds
[ Info:  started timer at: 2025-03-09T18:28:39.492


25
k : 6
1
-33093.30530113664
2569.0908466282995
25
K : 6
[0 -2800 -100 -1200 -2000]


[ Info:         1936.7220948s: 32 minutes, 16 seconds, 722 milliseconds
[ Info:  started timer at: 2025-03-09T19:00:56.247


25
k : 6
1
-35240.969819693564
2731.2703911155454
25
K : 6
[0 -3200 -100 -1200 -2000]


[ Info:         1950.0285187s: 32 minutes, 30 seconds, 28 milliseconds
[ Info:  started timer at: 2025-03-09T19:33:26.323


25
k : 6
1
-37510.85304775746
3014.585259029721
25
K : 8
[0 -800 -100 -1200 -2000]


[ Info:         1964.1076669s: 32 minutes, 44 seconds, 107 milliseconds
[ Info:  started timer at: 2025-03-09T20:06:10.465


25
k : 8
1
-22713.135698853246
1824.795665212377
25
K : 8
[0 -1200 -100 -1200 -2000]


[ Info:          1946.251306s: 32 minutes, 26 seconds, 251 milliseconds
[ Info:  started timer at: 2025-03-09T20:38:36.760


25
k : 8
1
-25702.667958685066
2007.758401274902
25
K : 8
[0 -1600 -100 -1200 -2000]


[ Info:         1957.0687357s: 32 minutes, 37 seconds, 68 milliseconds
[ Info:  started timer at: 2025-03-09T21:11:13.875


25
k : 8
1
-28146.33258124511
2132.498352547165
25
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:         1960.7440324s: 32 minutes, 40 seconds, 744 milliseconds
[ Info:  started timer at: 2025-03-09T21:43:54.660


25
k : 8
1
-30377.309581303583
2290.59841663501
25
K : 8
[0 -2400 -100 -1200 -2000]


[ Info:         1946.8695407s: 32 minutes, 26 seconds, 869 milliseconds
[ Info:  started timer at: 2025-03-09T22:16:21.558


25
k : 8
1
-32405.62464519986
2433.501736150443
25
K : 8
[0 -2800 -100 -1200 -2000]


[ Info:         1957.6070092s: 32 minutes, 37 seconds, 607 milliseconds
[ Info:  started timer at: 2025-03-09T22:48:59.206


25
k : 8
1
-34313.708704671306
2557.7832485317567
25
K : 8
[0 -3200 -100 -1200 -2000]


[ Info:         1962.0807392s: 32 minutes, 42 seconds, 80 milliseconds
[ Info:  started timer at: 2025-03-09T23:21:41.332


25
k : 8
1
-36282.52661001364
2746.094223498323
25
K : 10
[0 -800 -100 -1200 -2000]


[ Info:          1941.934884s: 32 minutes, 21 seconds, 934 milliseconds
[ Info:  started timer at: 2025-03-09T23:54:03.313


25
k : 10
1
-22657.902628371154
1791.7091073074769
25
K : 10
[0 -1200 -100 -1200 -2000]


[ Info:         1951.5639692s: 32 minutes, 31 seconds, 563 milliseconds
[ Info:  started timer at: 2025-03-10T00:26:34.922


25
k : 10
1
-25682.22981977704
2018.2037344927714
25
K : 10
[0 -1600 -100 -1200 -2000]


[ Info:         1948.5931911s: 32 minutes, 28 seconds, 593 milliseconds
[ Info:  started timer at: 2025-03-10T00:59:03.552


25
k : 10
1
-28049.312266517383
2124.2651082385005
25
K : 10
[0 -2000 -100 -1200 -2000]


[ Info:         1948.0861507s: 32 minutes, 28 seconds, 86 milliseconds
[ Info:  started timer at: 2025-03-10T01:31:31.679


25
k : 10
1
-30149.07997498598
2246.9867243716044
25
K : 10
[0 -2400 -100 -1200 -2000]


[ Info:         1965.8493123s: 32 minutes, 45 seconds, 849 milliseconds
[ Info:  started timer at: 2025-03-10T02:04:17.570


25
k : 10
1
-32129.950136382125
2330.4978567529965
25
K : 10
[0 -2800 -100 -1200 -2000]


[ Info:         1952.2235596s: 32 minutes, 32 seconds, 223 milliseconds
[ Info:  started timer at: 2025-03-10T02:36:49.831


25
k : 10
1
-33851.169576399836
2473.706525957773
25
K : 10
[0 -3200 -100 -1200 -2000]


[ Info:         1950.7403683s: 32 minutes, 30 seconds, 740 milliseconds
[ Info:  started timer at: 2025-03-10T03:09:20.610


25
k : 10
1
-35634.92264046454
2611.916162503416
25
K : 12
[0 -800 -100 -1200 -2000]


[ Info:         1953.9580423s: 32 minutes, 33 seconds, 958 milliseconds
[ Info:  started timer at: 2025-03-10T03:41:54.621


25
k : 12
1
-22589.41907792449
1814.3990567408555
25
K : 12
[0 -1200 -100 -1200 -2000]


[ Info:         1959.9734845s: 32 minutes, 39 seconds, 973 milliseconds
[ Info:  started timer at: 2025-03-10T04:14:34.630


25
k : 12
1
-25566.418806235135
1995.8399065242984
25
K : 12
[0 -1600 -100 -1200 -2000]


[ Info:         1959.4845226s: 32 minutes, 39 seconds, 484 milliseconds
[ Info:  started timer at: 2025-03-10T04:47:14.150


25
k : 12
1
-27963.613298569668
2109.5107658068614
25
K : 12
[0 -2000 -100 -1200 -2000]


[ Info:         1950.1441521s: 32 minutes, 30 seconds, 144 milliseconds
[ Info:  started timer at: 2025-03-10T05:19:44.333


25
k : 12
1
-30016.01274451548
2225.7326577892227
25
K : 12
[0 -2400 -100 -1200 -2000]


[ Info:         1955.9310036s: 32 minutes, 35 seconds, 931 milliseconds
[ Info:  started timer at: 2025-03-10T05:52:20.315


25
k : 12
1
-31912.235840941023
2308.3326850109875
25
K : 12
[0 -2800 -100 -1200 -2000]


[ Info:           1949.65282s: 32 minutes, 29 seconds, 652 milliseconds
[ Info:  started timer at: 2025-03-10T06:24:50.010


25
k : 12
1
-33599.28526623124
2390.464498292301
25
K : 12
[0 -3200 -100 -1200 -2000]


[ Info:         1962.7790389s: 32 minutes, 42 seconds, 779 milliseconds
[ Info:  started timer at: 2025-03-10T06:57:32.831


25
k : 12
1
-35230.09398233285
2504.503534739485
30
K : 2
[0 -800 -100 -1200 -2000]


[ Info:         1963.0231422s: 32 minutes, 43 seconds, 23 milliseconds
[ Info:  started timer at: 2025-03-10T07:30:15.893


30
k : 2
1
-30555.707474657764
2932.394384835069
30
K : 2
[0 -1200 -100 -1200 -2000]


[ Info:         2350.9587448s: 39 minutes, 10 seconds, 958 milliseconds
[ Info:  started timer at: 2025-03-10T08:09:26.905


30
k : 2
1
-36184.65411354238
3459.2033549821044
30
K : 2
[0 -1600 -100 -1200 -2000]


[ Info:         2335.6728518s: 38 minutes, 55 seconds, 672 milliseconds
[ Info:  started timer at: 2025-03-10T08:48:22.622


30
k : 2
1
-40566.88002643755
3723.985291438601
30
K : 2

[ Info:         2334.4847665s: 38 minutes, 54 seconds, 484 milliseconds
[ Info:  started timer at: 2025-03-10T09:27:17.154



[0 -2000 -100 -1200 -2000]
30
k : 2
1
-44303.11078929711
3882.5370091488926
30
K : 2
[0 -2400 -100 -1200 -2000]


[ Info:         2307.3161377s: 38 minutes, 27 seconds, 316 milliseconds
[ Info:  started timer at: 2025-03-10T10:05:44.517


30
k : 2
1
-47870.956416561705
4111.409861816678
30
K : 2
[0 -2800 -100 -1200 -2000]


[ Info:         2344.3645109s: 39 minutes, 4 seconds, 364 milliseconds
[ Info:  started timer at: 2025-03-10T10:44:48.943


30
k : 2
1
-51247.88660989049
4305.585628150751
30
K : 2
[0 -3200 -100 -1200 -2000]


[ Info:         2338.3248649s: 38 minutes, 58 seconds, 324 milliseconds
[ Info:  started timer at: 2025-03-10T11:23:47.317


30
k : 2
1
-54206.29129634397
4385.199776265147


[ Info:          2350.381479s: 39 minutes, 10 seconds, 381 milliseconds


30
K : 4
[0 -800 -100 -1200 -2000]


[ Info:  started timer at: 2025-03-10T12:02:57.744


30
k : 4
1
-27040.55327091217
2066.6412921179935
30
K : 4
[0 -1200 -100 -1200 -2000]


[ Info:         2335.8136749s: 38 minutes, 55 seconds, 813 milliseconds
[ Info:  started timer at: 2025-03-10T12:41:53.599


30
k : 4
1
-31031.01988097228
2424.1303605823364
30
K : 4
[0 -1600 -100 -1200 -2000]


[ Info:         2354.8707711s: 39 minutes, 14 seconds, 870 milliseconds
[ Info:  started timer at: 2025-03-10T13:21:08.533


30
k : 4
1
-34556.69333760917
2671.117678439411
30
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:         2361.7758224s: 39 minutes, 21 seconds, 775 milliseconds
[ Info:  started timer at: 2025-03-10T14:00:30.350


30
k : 4
1
-37620.23279276786
2975.9853148163074
30
K : 4
[0 -2400 -100 -1200 -2000]


[ Info:         2347.8942803s: 39 minutes, 7 seconds, 894 milliseconds
[ Info:  started timer at: 2025-03-10T14:39:38.302


30
k : 4
1
-40632.013174386826
3230.5059341745255
30
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:         2347.2530335s: 39 minutes, 7 seconds, 253 milliseconds
[ Info:  started timer at: 2025-03-10T15:18:45.593


30
k : 4
1
-43632.23763256321
3481.300122976049
30
K : 4
[0 -3200 -100 -1200 -2000]


[ Info:         2366.1722292s: 39 minutes, 26 seconds, 172 milliseconds
[ Info:  started timer at: 2025-03-10T15:58:11.815


30
k : 4
1
-46339.023515168956
3714.070854808306
30
K : 6
[0 -800 -100 -1200 -2000]


[ Info:         2350.5669574s: 39 minutes, 10 seconds, 566 milliseconds
[ Info:  started timer at: 2025-03-10T16:37:22.431


30
k : 6
1
-26709.598941559576
1943.1665234668153
30
K : 6
[0 -1200 -100 -1200 -2000]


[ Info:         2355.4997901s: 39 minutes, 15 seconds, 499 milliseconds
[ Info:  started timer at: 2025-03-10T17:16:37.981


30
k : 6
1
-30258.96170697899
2207.6009563405105
30
K : 6
[0 -1600 -100 -1200 -2000]


[ Info:         2394.2451491s: 39 minutes, 54 seconds, 245 milliseconds
[ Info:  started timer at: 2025-03-10T17:56:32.283


30
k : 6
1
-33327.70575234521
2422.146274187927
30
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:         2373.1513565s: 39 minutes, 33 seconds, 151 milliseconds
[ Info:  started timer at: 2025-03-10T18:36:05.486


30
k : 6
1
-35887.3304393527
2547.207703120307
30
K : 6
[0 -2400 -100 -1200 -2000]


[ Info:         2327.6409443s: 38 minutes, 47 seconds, 640 milliseconds
[ Info:  started timer at: 2025-03-10T19:14:53.171


30
k : 6
1
-38388.53510123
2764.1077046872583
30
K : 6
[0 -2800 -100 -1200 -2000]


[ Info:          2360.464847s: 39 minutes, 20 seconds, 464 milliseconds
[ Info:  started timer at: 2025-03-10T19:54:13.686


30
k : 6
1
-40901.71671595191
2991.008878065181
30
K : 6
[0 -3200 -100 -1200 -2000]


[ Info:         2328.7563129s: 38 minutes, 48 seconds, 756 milliseconds
[ Info:  started timer at: 2025-03-10T20:33:02.489


30
k : 6
1
-43310.967529673326
3184.758626838158
30
K : 8
[0 -800 -100 -1200 -2000]


[ Info:         2346.2824402s: 39 minutes, 6 seconds, 282 milliseconds
[ Info:  started timer at: 2025-03-10T21:12:08.832


30
k : 8
1
-26556.129297611198
1921.1230618220645
30
K : 8
[0 -1200 -100 -1200 -2000]


[ Info:         2335.6258093s: 38 minutes, 55 seconds, 625 milliseconds
[ Info:  started timer at: 2025-03-10T21:51:04.501


30
k : 8
1
-30014.501130093013
2151.2623637418815
30
K : 8
[0 -1600 -100 -1200 -2000]


[ Info:         2356.1758889s: 39 minutes, 16 seconds, 175 milliseconds
[ Info:  started timer at: 2025-03-10T22:30:20.735


30
k : 8
1
-32942.86152324028
2282.0195669978443
30
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:         2342.3792115s: 39 minutes, 2 seconds, 379 milliseconds
[ Info:  started timer at: 2025-03-10T23:09:23.154


30
k : 8
1
-35311.154809086634
2452.6008442674934
30
K : 8
[0 -2400 -100 -1200 -2000]


[ Info:         2352.1585037s: 39 minutes, 12 seconds, 158 milliseconds
[ Info:  started timer at: 2025-03-10T23:48:35.360


30
k : 8
1
-37607.81479194946
2611.112287724164
30
K : 8
[0 -2800 -100 -1200 -2000]


[ Info:         2350.0307236s: 39 minutes, 10 seconds, 30 milliseconds
[ Info:  started timer at: 2025-03-11T00:27:45.451


30
k : 8
1
-39840.37649328465
2785.105758337119
30
K : 8
[0 -3200 -100 -1200 -2000]


[ Info:         2361.4286457s: 39 minutes, 21 seconds, 428 milliseconds
[ Info:  started timer at: 2025-03-11T01:07:06.915


30
k : 8
1
-41913.82214655797
2967.8678639835
30
K : 10
[0 -800 -100 -1200 -2000]


[ Info:         2361.0845729s: 39 minutes, 21 seconds, 84 milliseconds
[ Info:  started timer at: 2025-03-11T01:46:28.057


30
k : 10
1
-26494.8368974668
1927.715185960298
30
K : 10
[0 -1200 -100 -1200 -2000]


[ Info:         2365.4434567s: 39 minutes, 25 seconds, 443 milliseconds
[ Info:  started timer at: 2025-03-11T02:25:53.558


30
k : 10
1
-29956.138800493813
2135.251311124488
30
K : 10
[0 -1600 -100 -1200 -2000]


[ Info:         2363.4608287s: 39 minutes, 23 seconds, 460 milliseconds
[ Info:  started timer at: 2025-03-11T03:05:17.054


30
k : 10
1
-32762.54535109368
2285.666161339414
30
K : 10
[0 -2000 -100 -1200 -2000]


[ Info:         2370.0397902s: 39 minutes, 30 seconds, 39 milliseconds
[ Info:  started timer at: 2025-03-11T03:44:47.146


30
k : 10
1
-35088.0963217355
2374.4608002777068
30
K : 10
[0 -2400 -100 -1200 -2000]


[ Info:         2358.5377011s: 39 minutes, 18 seconds, 537 milliseconds
[ Info:  started timer at: 2025-03-11T04:24:05.743


30
k : 10
1
-37227.536841497844
2528.554577316513
30
K : 10
[0 -2800 -100 -1200 -2000]


[ Info:         2364.6439608s: 39 minutes, 24 seconds, 643 milliseconds
[ Info:  started timer at: 2025-03-11T05:03:30.435


30
k : 10
1
-39327.943805993746
2666.7003618592576
30
K : 10
[0 -3200 -100 -1200 -2000]


[ Info:         2349.0753819s: 39 minutes, 9 seconds, 75 milliseconds
[ Info:  started timer at: 2025-03-11T05:42:39.560


30
k : 10
1
-41211.37316128962
2786.533884248857
30
K : 12
[0 -800 -100 -1200 -2000]


[ Info:         2347.3684549s: 39 minutes, 7 seconds, 368 milliseconds
[ Info:  started timer at: 2025-03-11T06:21:47.009


30
k : 12
1
-26519.436685656696
1926.4060289135
30
K : 12
[0 -1200 -100 -1200 -2000]


[ Info:         2337.4261431s: 38 minutes, 57 seconds, 426 milliseconds
[ Info:  started timer at: 2025-03-11T07:00:44.483


30
k : 12
1
-29908.62363419396
2131.305001891442
30
K : 12
[0 -1600 -100 -1200 -2000]


[ Info:         2358.8310749s: 39 minutes, 18 seconds, 831 milliseconds
[ Info:  started timer at: 2025-03-11T07:40:03.381


30
k : 12
1
-32716.998598009963
2289.562260920928
30
K : 12
[0 -2000 -100 -1200 -2000]


[ Info:         2355.7509039s: 39 minutes, 15 seconds, 750 milliseconds
[ Info:  started timer at: 2025-03-11T08:19:19.182


30
k : 12
1
-34924.309374820645
2381.8594565066246
30
K : 12
[0 -2400 -100 -1200 -2000]


[ Info:         2363.3004603s: 39 minutes, 23 seconds, 300 milliseconds
[ Info:  started timer at: 2025-03-11T08:58:42.531


30
k : 12
1
-37041.68070273423
2495.3286143862324
30
K : 12
[0 -2800 -100 -1200 -2000]


[ Info:         2350.8516543s: 39 minutes, 10 seconds, 851 milliseconds
[ Info:  started timer at: 2025-03-11T09:37:53.432


30
k : 12
1
-39031.671480317455
2620.233275515046
30
K : 12
[0 -3200 -100 -1200 -2000]


[ Info:         2376.8617133s: 39 minutes, 36 seconds, 861 milliseconds
[ Info:  started timer at: 2025-03-11T10:17:30.346


30
k : 12
1
-40847.805624626264
2719.0249346333835
30
K : 14
[0 -800 -100 -1200 -2000]


[ Info:         2359.2015331s: 39 minutes, 19 seconds, 201 milliseconds
[ Info:  started timer at: 2025-03-11T10:56:49.597


30
k : 14
1
-26485.858338052803
1927.5442147725391
30
K : 14
[0 -1200 -100 -1200 -2000]


[ Info:         2376.5617522s: 39 minutes, 36 seconds, 561 milliseconds
[ Info:  started timer at: 2025-03-11T11:36:26.206


30
k : 14
1
-29852.378245942724
2144.628098610424
30
K : 14
[0 -1600 -100 -1200 -2000]


[ Info:         2391.9416103s: 39 minutes, 51 seconds, 941 milliseconds
[ Info:  started timer at: 2025-03-11T12:16:18.201


30
k : 14
1
-32658.61991543954
2280.9053338718663
30
K : 14
[0 -2000 -100 -1200 -2000]


[ Info:         2395.3585017s: 39 minutes, 55 seconds, 358 milliseconds
[ Info:  started timer at: 2025-03-11T12:56:13.610


30
k : 14
1
-34872.45106831225
2383.4302224005924
30
K : 14
[0 -2400 -100 -1200 -2000]


[ Info:         2412.9454415s: 40 minutes, 12 seconds, 945 milliseconds
[ Info:  started timer at: 2025-03-11T13:36:26.606


30
k : 14
1
-36944.48595348656
2477.786176989661
30
K : 14
[0 -2800 -100 -1200 -2000]


[ Info:         2409.0977442s: 40 minutes, 9 seconds, 97 milliseconds
[ Info:  started timer at: 2025-03-11T14:16:35.755


30
k : 14
1
-38893.18274582554
2589.385480888972
30
K : 14
[0 -3200 -100 -1200 -2000]


[ Info:         2419.8708927s: 40 minutes, 19 seconds, 870 milliseconds
[ Info:  started timer at: 2025-03-11T14:56:55.664


30
k : 14
1
-40558.52989420604
2659.5775502719266
40
K : 2
[0 -800 -100 -1200 -2000]


[ Info:         2387.0568191s: 39 minutes, 47 seconds, 56 milliseconds
[ Info:  started timer at: 2025-03-11T15:36:42.776


40
k : 2
1
-35571.156533880116
3068.9769764203174
40
K : 2
[0 -1200 -100 -1200 -2000]


[ Info:          3149.318381s: 52 minutes, 29 seconds, 318 milliseconds
[ Info:  started timer at: 2025-03-11T16:29:12.171


40
k : 2
1
-42023.9240479454
3610.164379114443
40
K : 2
[0 -1600 -100 -1200 -2000]


[ Info:         3094.8196946s: 51 minutes, 34 seconds, 819 milliseconds
[ Info:  started timer at: 2025-03-11T17:20:47.048


40
k : 2
1
-47279.95071697306
4012.485742632357
40
K : 2
[0 -2000 -100 -1200 -2000]


[ Info:         3138.1038675s: 52 minutes, 18 seconds, 103 milliseconds
[ Info:  started timer at: 2025-03-11T18:13:05.226


40
k : 2
1
-51421.88725161537
4160.1912864452925
40
K : 2
[0 -2400 -100 -1200 -2000]


[ Info:          3123.714568s: 52 minutes, 3 seconds, 714 milliseconds
[ Info:  started timer at: 2025-03-11T19:05:09.007


40
k : 2
1
-55092.90700781693
4285.223643059436
40
K : 2
[0 -2800 -100 -1200 -2000]


[ Info:         3142.3751949s: 52 minutes, 22 seconds, 375 milliseconds
[ Info:  started timer at: 2025-03-11T19:57:31.434


40
k : 2
1
-58454.25014670472
4336.236788916728
40

[ Info:         3145.7772901s: 52 minutes, 25 seconds, 777 milliseconds
[ Info:  started timer at: 2025-03-11T20:49:57.290



K : 2
[0 -3200 -100 -1200 -2000]
40
k : 2
1
-61785.049607395194
4520.446919877816
40
K : 4
[0 -800 -100 -1200 -2000]


[ Info:         3145.3790894s: 52 minutes, 25 seconds, 379 milliseconds
[ Info:  started timer at: 2025-03-11T21:42:22.724


40
k : 4
1
-31850.907647200907
2178.3874233976962
40
K : 4
[0 -1200 -100 -1200 -2000]


[ Info:         3136.9456852s: 52 minutes, 16 seconds, 945 milliseconds
[ Info:  started timer at: 2025-03-11T22:34:39.739


40
k : 4
1
-36600.2390395652
2619.4330810858773
40

[ Info:         3141.5237046s: 52 minutes, 21 seconds, 523 milliseconds
[ Info:  started timer at: 2025-03-11T23:27:01.336



K : 4
[0 -1600 -100 -1200 -2000]
40
k : 4
1
-40660.986878458716
2969.3679097306876
40
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:         3154.2412815s: 52 minutes, 34 seconds, 241 milliseconds
[ Info:  started timer at: 2025-03-12T00:19:35.643


40
k : 4
1
-44257.569269746964
3238.6629273191925
40
K : 4
[0 -2400 -100 -1200 -2000]


[ Info:         3172.6387307s: 52 minutes, 52 seconds, 638 milliseconds
[ Info:  started timer at: 2025-03-12T01:12:28.343


40
k : 4
1
-47600.25537086347
3502.9072737999427
40
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:         3170.5860742s: 52 minutes, 50 seconds, 586 milliseconds
[ Info:  started timer at: 2025-03-12T02:05:19.002


40
k : 4
1
-50840.393761713014
3720.039404741189
40
K : 4
[0 -3200 -100 -1200 -2000]


[ Info:         3136.9915825s: 52 minutes, 16 seconds, 991 milliseconds
[ Info:  started timer at: 2025-03-12T02:57:36.055


40
k : 4
1
-53910.6524190732
3892.9317182263603
40
K : 6
[0 -800 -100 -1200 -2000]


[ Info:         3178.2365474s: 52 minutes, 58 seconds, 236 milliseconds
[ Info:  started timer at: 2025-03-12T03:50:34.356


40
k : 6
1
-31426.426918794572
2046.4994714800857
40
K : 6
[0 -1200 -100 -1200 -2000]


[ Info:         3135.8228057s: 52 minutes, 15 seconds, 822 milliseconds
[ Info:  started timer at: 2025-03-12T04:42:50.249


40
k : 6
1
-35665.09742654388
2350.967593541984
40
K : 6
[0 -1600 -100 -1200 -2000]


[ Info:         3162.0821532s: 52 minutes, 42 seconds, 82 milliseconds
[ Info:  started timer at: 2025-03-12T05:35:32.399


40
k : 6
1
-39188.42773006332
2631.9836378953382
40
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:         3149.4772868s: 52 minutes, 29 seconds, 477 milliseconds
[ Info:  started timer at: 2025-03-12T06:28:01.954


40
k : 6
1
-42302.48862240859
2795.7643987794954
40
K : 6
[0 -2400 -100 -1200 -2000]


[ Info:         3179.3092134s: 52 minutes, 59 seconds, 309 milliseconds
[ Info:  started timer at: 2025-03-12T07:21:01.354


40
k : 6
1
-45121.46370257062
3048.5285322029886
40
K : 6
[0 -2800 -100 -1200 -2000]


[ Info:         3148.6582092s: 52 minutes, 28 seconds, 658 milliseconds
[ Info:  started timer at: 2025-03-12T08:13:30.078


40
k : 6
1
-47989.26494116549
3208.305570985292
40
K : 6
[0 -3200 -100 -1200 -2000]


[ Info:         3174.2557846s: 52 minutes, 54 seconds, 255 milliseconds
[ Info:  started timer at: 2025-03-12T09:06:24.399


40
k : 6
1
-50725.778868315196
3519.1678037337942
40
K : 8
[0 -800 -100 -1200 -2000]


[ Info:         3168.1886517s: 52 minutes, 48 seconds, 188 milliseconds
[ Info:  started timer at: 2025-03-12T09:59:12.657


40
k : 8
1
-31372.634523301484
2026.762976229344
40
K : 8
[0 -1200 -100 -1200 -2000]


[ Info:         3158.9850436s: 52 minutes, 38 seconds, 985 milliseconds
[ Info:  started timer at: 2025-03-12T10:51:51.707


40
k : 8
1
-35437.435905981525
2311.3508679964907
40
K : 8
[0 -1600 -100 -1200 -2000]


[ Info:         3204.4725444s: 53 minutes, 24 seconds, 472 milliseconds
[ Info:  started timer at: 2025-03-12T11:45:16.247


40
k : 8
1
-38745.34532016465
2502.9593249975924
40
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:         3177.1232848s: 52 minutes, 57 seconds, 123 milliseconds
[ Info:  started timer at: 2025-03-12T12:38:13.439


40
k : 8
1
-41622.95821542688
2628.535962544609
40
K : 8
[0 -2400 -100 -1200 -2000]


[ Info:         3185.9953214s: 53 minutes, 5 seconds, 995 milliseconds
[ Info:  started timer at: 2025-03-12T13:31:19.502


40
k : 8
1
-44220.70073073882
2818.808168319077
40
K : 8
[0 -2800 -100 -1200 -2000]


[ Info:         3172.4270747s: 52 minutes, 52 seconds, 427 milliseconds
[ Info:  started timer at: 2025-03-12T14:24:11.980


40
k : 8
1
-46748.93155512522
2997.4108991347916
40
K : 8
[0 -3200 -100 -1200 -2000]


[ Info:         3191.3509352s: 53 minutes, 11 seconds, 350 milliseconds
[ Info:  started timer at: 2025-03-12T15:17:23.407


40
k : 8
1
-49075.056768862116
3168.2635336705503
40
K : 10
[0 -800 -100 -1200 -2000]


[ Info:         3171.6719747s: 52 minutes, 51 seconds, 671 milliseconds
[ Info:  started timer at: 2025-03-12T16:10:15.151


40
k : 10
1
-31321.512778493685
2044.5071248202528
40
K : 10
[0 -1200 -100 -1200 -2000]


[ Info:         3197.0976647s: 53 minutes, 17 seconds, 97 milliseconds
[ Info:  started timer at: 2025-03-12T17:03:32.306


40
k : 10
1
-35361.962108656946
2271.5756350078773
40
K : 10
[0 -1600 -100 -1200 -2000]


[ Info:         3186.7548047s: 53 minutes, 6 seconds, 754 milliseconds
[ Info:  started timer at: 2025-03-12T17:56:39.138


40
k : 10
1
-38566.28473632286
2484.3468299833944
40
K : 10
[0 -2000 -100 -1200 -2000]


[ Info:         3228.6421601s: 53 minutes, 48 seconds, 642 milliseconds
[ Info:  started timer at: 2025-03-12T18:50:27.847


40
k : 10
1
-41376.02081001216
2611.656157684993
40
K : 10
[0 -2400 -100 -1200 -2000]


[ Info:         3189.7249589s: 53 minutes, 9 seconds, 724 milliseconds
[ Info:  started timer at: 2025-03-12T19:43:37.651


40
k : 10
1
-43800.52166382111
2732.93571394785
40
K : 10
[0 -2800 -100 -1200 -2000]


[ Info:         3207.2632823s: 53 minutes, 27 seconds, 263 milliseconds
[ Info:  started timer at: 2025-03-12T20:37:04.981


40
k : 10
1
-46081.68208016883
2894.7974347595823
40
K : 10
[0 -3200 -100 -1200 -2000]


[ Info:          3226.586833s: 53 minutes, 46 seconds, 586 milliseconds
[ Info:  started timer at: 2025-03-12T21:30:51.637


40
k : 10
1
-48344.361947900055
3007.7951962685684
40
K : 12
[0 -800 -100 -1200 -2000]


[ Info:         3182.0647108s: 53 minutes, 2 seconds, 64 milliseconds
[ Info:  started timer at: 2025-03-12T22:23:53.769


40
k : 12
1
-31242.579085484325
2027.7934286988445
40
K : 12
[0 -1200 -100 -1200 -2000]


[ Info:         3228.6832496s: 53 minutes, 48 seconds, 683 milliseconds
[ Info:  started timer at: 2025-03-12T23:17:42.520


40
k : 12
1
-35289.85990123099
2316.505625871897
40
K : 12
[0 -1600 -100 -1200 -2000]


[ Info:         3207.2985435s: 53 minutes, 27 seconds, 298 milliseconds
[ Info:  started timer at: 2025-03-13T00:11:09.885


40
k : 12
1
-38503.219157319356
2486.0073426627564
40
K : 12
[0 -2000 -100 -1200 -2000]


[ Info:         3235.7804357s: 53 minutes, 55 seconds, 780 milliseconds
[ Info:  started timer at: 2025-03-13T01:05:05.733


40
k : 12
1
-41235.50201736067
2596.055907381723
40
K : 12
[0 -2400 -100 -1200 -2000]


[ Info:          3225.244986s: 53 minutes, 45 seconds, 244 milliseconds
[ Info:  started timer at: 2025-03-13T01:58:51.046


40
k : 12
1
-43640.651533584576
2698.477276148524
40
K : 12
[0 -2800 -100 -1200 -2000]


[ Info:         3226.6604058s: 53 minutes, 46 seconds, 660 milliseconds
[ Info:  started timer at: 2025-03-13T02:52:37.773


40
k : 12
1
-45831.244624356106
2828.188459106234


[ Info:         3236.3505603s: 53 minutes, 56 seconds, 350 milliseconds


40
K : 12
[0 -3200 -100 -1200 -2000]


[ Info:  started timer at: 2025-03-13T03:46:34.202


40
k : 12
1
-47984.959188760935
2936.633701322647
40
K : 14
[0 -800 -100 -1200 -2000]


[ Info:         3207.0695422s: 53 minutes, 27 seconds, 69 milliseconds
[ Info:  started timer at: 2025-03-13T04:40:01.338


40
k : 14
1
-31244.476534848374
2030.3771505036705
40
K : 14
[0 -1200 -100 -1200 -2000]


[ Info:          3221.075411s: 53 minutes, 41 seconds, 75 milliseconds
[ Info:  started timer at: 2025-03-13T05:33:42.481


40
k : 14
1
-35290.958162103976
2303.3487551135645
40
K : 14
[0 -1600 -100 -1200 -2000]


[ Info:          3231.060217s: 53 minutes, 51 seconds, 60 milliseconds
[ Info:  started timer at: 2025-03-13T06:27:33.609


40
k : 14
1
-38506.127391404094
2480.37519274286
40
K : 14
[0 -2000 -100 -1200 -2000]


[ Info:         3241.2210178s: 54 minutes, 1 second, 221 milliseconds
[ Info:  started timer at: 2025-03-13T07:21:34.898


40
k : 14
1
-41163.205159284866
2571.112938621291
40
K : 14
[0 -2400 -100 -1200 -2000]


[ Info:         3294.9907761s: 54 minutes, 54 seconds, 990 milliseconds
[ Info:  started timer at: 2025-03-13T08:16:29.969


40
k : 14
1
-43527.280741519484
2707.1771159582995
40
K : 14
[0 -2800 -100 -1200 -2000]


[ Info:         3246.9190609s: 54 minutes, 6 seconds, 919 milliseconds
[ Info:  started timer at: 2025-03-13T09:10:36.955


40
k : 14
1
-45686.92145587017
2785.6167768467594
40
K : 14
[0 -3200 -100 -1200 -2000]


[ Info:         3259.0332217s: 54 minutes, 19 seconds, 33 milliseconds
[ Info:  started timer at: 2025-03-13T10:04:56.056


40
k : 14
1
-47751.52726631993
2946.99518709063
40
K : 16
[0 -800 -100 -1200 -2000]


[ Info:         3271.1455992s: 54 minutes, 31 seconds, 145 milliseconds
[ Info:  started timer at: 2025-03-13T10:59:27.271


40
k : 16
1
-31228.556898688857
2038.597891012583
40
K : 16
[0 -1200 -100 -1200 -2000]


[ Info:         3247.7014599s: 54 minutes, 7 seconds, 701 milliseconds
[ Info:  started timer at: 2025-03-13T11:53:35.041


40
k : 16
1
-35255.93318331273
2304.2926805843495
40
K : 16
[0 -1600 -100 -1200 -2000]


[ Info:         3248.5462295s: 54 minutes, 8 seconds, 546 milliseconds
[ Info:  started timer at: 2025-03-13T12:47:43.656


40
k : 16
1
-38469.59157302172
2471.5007071171176
40
K : 16
[0 -2000 -100 -1200 -2000]


[ Info:           3258.03163s: 54 minutes, 18 seconds, 31 milliseconds
[ Info:  started timer at: 2025-03-13T13:42:01.756


40
k : 16
1
-41128.33624758036
2590.0533810768948
40
K : 16
[0 -2400 -100 -1200 -2000]


[ Info:          3244.717713s: 54 minutes, 4 seconds, 717 milliseconds
[ Info:  started timer at: 2025-03-13T14:36:06.542


40
k : 16
1
-43412.20845874053
2679.454455535184
40
K : 16
[0 -2800 -100 -1200 -2000]


[ Info:         3272.0944328s: 54 minutes, 32 seconds, 94 milliseconds
[ Info:  started timer at: 2025-03-13T15:30:38.705


40
k : 16
1
-45595.26430728167
2789.379706755744
40
K : 16
[0 -3200 -100 -1200 -2000]


[ Info:         3222.1056153s: 53 minutes, 42 seconds, 105 milliseconds
[ Info:  started timer at: 2025-03-13T16:24:20.879


40
k : 16
1
-47561.52665719061
2863.9380377567745
40
K : 18
[0 -800 -100 -1200 -2000]


[ Info:         3257.5100598s: 54 minutes, 17 seconds, 510 milliseconds
[ Info:  started timer at: 2025-03-13T17:18:38.458


40
k : 18
1
-31239.98626685584
2026.843397912462
40
K : 18
[0 -1200 -100 -1200 -2000]


[ Info:         3292.6881739s: 54 minutes, 52 seconds, 688 milliseconds
[ Info:  started timer at: 2025-03-13T18:13:31.215


40
k : 18
1
-35221.71611371562
2280.0715353192804
40
K : 18
[0 -1600 -100 -1200 -2000]


[ Info:         3262.1705463s: 54 minutes, 22 seconds, 170 milliseconds
[ Info:  started timer at: 2025-03-13T19:07:53.455


40
k : 18
1
-38354.794772105226
2476.819355079381
40
K : 18
[0 -2000 -100 -1200 -2000]


[ Info:         3287.2310774s: 54 minutes, 47 seconds, 231 milliseconds
[ Info:  started timer at: 2025-03-13T20:02:40.754


40
k : 18
1
-41076.372259848395
2626.700402234903
40
K : 18
[0 -2400 -100 -1200 -2000]


[ Info:         3318.2079478s: 55 minutes, 18 seconds, 207 milliseconds
[ Info:  started timer at: 2025-03-13T20:57:59.032


40
k : 18
1
-43371.384353953006
2713.404800242571
40
K : 18
[0 -2800 -100 -1200 -2000]


[ Info:         3288.5486532s: 54 minutes, 48 seconds, 548 milliseconds
[ Info:  started timer at: 2025-03-13T21:52:47.649


40
k : 18
1
-45470.17700542254
2840.36493705566
40
K : 18
[0 -3200 -100 -1200 -2000]


[ Info:         3325.0841853s: 55 minutes, 25 seconds, 84 milliseconds
[ Info:  started timer at: 2025-03-13T22:48:12.804


40
k : 18
1
-47493.792318391104
3057.6297479104737
40
K : 20
[0 -800 -100 -1200 -2000]


[ Info:         3302.1116598s: 55 minutes, 2 seconds, 111 milliseconds
[ Info:  started timer at: 2025-03-13T23:43:14.986


40
k : 20
1
-31200.219902981196
2049.2888000152725
40
K : 20
[0 -1200 -100 -1200 -2000]


[ Info:         3278.0219826s: 54 minutes, 38 seconds, 21 milliseconds
[ Info:  started timer at: 2025-03-14T00:37:53.077


40
k : 20
1
-35155.78720815315
2326.1623815550934
40
K : 20
[0 -1600 -100 -1200 -2000]


[ Info:         3310.6176369s: 55 minutes, 10 seconds, 617 milliseconds
[ Info:  started timer at: 2025-03-14T01:33:03.764


40
k : 20
1
-38343.12735487025
2489.6173423796577
40
K : 20
[0 -2000 -100 -1200 -2000]


[ Info:          3326.580905s: 55 minutes, 26 seconds, 580 milliseconds
[ Info:  started timer at: 2025-03-14T02:28:30.414


40
k : 20
1
-41058.438971574404
2697.7609741011624
40
K : 20
[0 -2400 -100 -1200 -2000]


[ Info:         3305.1671643s: 55 minutes, 5 seconds, 167 milliseconds
[ Info:  started timer at: 2025-03-14T03:23:35.650


40
k : 20
1
-43630.20202136172
2891.6100817043834
40
K : 20
[0 -2800 -100 -1200 -2000]


[ Info:         3337.5970823s: 55 minutes, 37 seconds, 597 milliseconds
[ Info:  started timer at: 2025-03-14T04:19:13.328


40
k : 20
1
-46556.0932165258
3306.631961846744
40
K : 20
[0 -3200 -100 -1200 -2000]


[ Info:         3301.9029916s: 55 minutes, 1 second, 902 milliseconds
[ Info:  started timer at: 2025-03-14T05:14:15.298


40
k : 20
1
-50067.12811328848
3755.6583652888976
50
K : 2
[0 -800 -100 -1200 -2000]


[ Info:         3280.8951428s: 54 minutes, 40 seconds, 895 milliseconds
[ Info:  started timer at: 2025-03-14T06:08:56.262


50
k : 2
1
-41160.63092645362
2980.574085780702
50
K : 2
[0 -1200 -100 -1200 -2000]


[ Info:         4141.5942171s: 1 hour, 9 minutes, 1 second, 594 milliseconds
[ Info:  started timer at: 2025-03-14T07:17:57.955


50
k : 2
1
-49047.82493148368
3612.9353234502914
50
K : 2
[0 -1600 -100 -1200 -2000]


[ Info:         4030.6468765s: 1 hour, 7 minutes, 10 seconds, 646 milliseconds
[ Info:  started timer at: 2025-03-14T08:25:08.686


50
k : 2
1
-55621.201857398286
4111.909823830049
50
K : 2
[0 -2000 -100 -1200 -2000]


[ Info:         4063.2346111s: 1 hour, 7 minutes, 43 seconds, 234 milliseconds
[ Info:  started timer at: 2025-03-14T09:32:52.007


50
k : 2
1
-60683.47145513046
4337.088396042855
50
K : 2
[0 -2400 -100 -1200 -2000]


[ Info:         4072.5707256s: 1 hour, 7 minutes, 52 seconds, 570 milliseconds
[ Info:  started timer at: 2025-03-14T10:40:44.663


50
k : 2
1
-64472.917199405754
4470.920850674894
50
K : 2
[0 -2800 -100 -1200 -2000]


[ Info:         4064.8263353s: 1 hour, 7 minutes, 44 seconds, 826 milliseconds
[ Info:  started timer at: 2025-03-14T11:48:29.574


50
k : 2
1
-67978.2936586633
4528.512173796266
50
K : 2
[0 -3200 -100 -1200 -2000]


[ Info:         4091.1668094s: 1 hour, 8 minutes, 11 seconds, 166 milliseconds
[ Info:  started timer at: 2025-03-14T12:56:40.826


50
k : 2
1
-71139.68774361306
4604.305511921061
50
K : 4
[0 -800 -100 -1200 -2000]


[ Info:         4054.8831559s: 1 hour, 7 minutes, 34 seconds, 883 milliseconds
[ Info:  started timer at: 2025-03-14T14:04:15.793


50
k : 4
1
-37821.06179534645
2145.4628275259174
50
K : 4
[0 -1200 -100 -1200 -2000]


[ Info:         4076.0731325s: 1 hour, 7 minutes, 56 seconds, 73 milliseconds
[ Info:  started timer at: 2025-03-14T15:12:11.952


50
k : 4
1
-43553.057576295985
2662.6911537457017
50
K : 4
[0 -1600 -100 -1200 -2000]


[ Info:         4079.8556769s: 1 hour, 7 minutes, 59 seconds, 855 milliseconds
[ Info:  started timer at: 2025-03-14T16:20:11.892


50
k : 4
1
-48439.87880940487
3150.5154399089797
50
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:         4042.4945554s: 1 hour, 7 minutes, 22 seconds, 494 milliseconds
[ Info:  started timer at: 2025-03-14T17:27:34.470


50
k : 4
1
-52687.15802848278
3420.7013153218645
50
K : 4
[0 -2400 -100 -1200 -2000]


[ Info:          4112.116585s: 1 hour, 8 minutes, 32 seconds, 116 milliseconds
[ Info:  started timer at: 2025-03-14T18:36:06.672


50
k : 4
1
-56214.96941498316
3611.3019094866154
50
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:         4137.0518679s: 1 hour, 8 minutes, 57 seconds, 51 milliseconds
[ Info:  started timer at: 2025-03-14T19:45:03.810


50
k : 4
1
-59716.04480269141
3783.627233483838
50
K : 4
[0 -3200 -100 -1200 -2000]


[ Info:         4139.6390233s: 1 hour, 8 minutes, 59 seconds, 639 milliseconds
[ Info:  started timer at: 2025-03-14T20:54:03.546


50
k : 4
1
-62974.0591593688
3971.5357877585443
50
K : 6
[0 -800 -100 -1200 -2000]


[ Info:         4256.1450432s: 1 hour, 10 minutes, 56 seconds, 145 milliseconds
[ Info:  started timer at: 2025-03-14T22:04:59.778


50
k : 6
1
-37473.028267561196
2076.432015763408
50
K : 6
[0 -1200 -100 -1200 -2000]


[ Info:         4218.3663162s: 1 hour, 10 minutes, 18 seconds, 366 milliseconds
[ Info:  started timer at: 2025-03-14T23:15:18.233


50
k : 6
1
-42555.40269380357
2442.9279305667133
50
K : 6
[0 -1600 -100 -1200 -2000]


[ Info:         4137.8543026s: 1 hour, 8 minutes, 57 seconds, 854 milliseconds
[ Info:  started timer at: 2025-03-15T00:24:16.174


50
k : 6
1
-46802.714400102916
2753.4162922460955
50
K : 6
[0 -2000 -100 -1200 -2000]


[ Info:          4199.531993s: 1 hour, 9 minutes, 59 seconds, 531 milliseconds
[ Info:  started timer at: 2025-03-15T01:34:15.792


50
k : 6
1
-50477.24189372592
2954.254168293857
50
K : 6
[0 -2400 -100 -1200 -2000]


[ Info:         4227.1917519s: 1 hour, 10 minutes, 27 seconds, 191 milliseconds
[ Info:  started timer at: 2025-03-15T02:44:43.071


50
k : 6
1
-53562.08612003008
3173.6995452831898
50
K : 6
[0 -2800 -100 -1200 -2000]


[ Info:         4207.5602419s: 1 hour, 10 minutes, 7 seconds, 560 milliseconds
[ Info:  started timer at: 2025-03-15T03:54:50.719


50
k : 6
1
-56803.44410756819
3380.281206095709
50
K : 6
[0 -3200 -100 -1200 -2000]


[ Info:         4294.1906916s: 1 hour, 11 minutes, 34 seconds, 190 milliseconds
[ Info:  started timer at: 2025-03-15T05:06:25.001


50
k : 6
1
-59665.6155494839
3564.2659660264576
50
K : 8
[0 -800 -100 -1200 -2000]


[ Info:         4283.9823442s: 1 hour, 11 minutes, 23 seconds, 982 milliseconds
[ Info:  started timer at: 2025-03-15T06:17:49.073


50
k : 8
1
-37459.422969993604
2054.693579081946


[ Info:         4283.1352049s: 1 hour, 11 minutes, 23 seconds, 135 milliseconds
[ Info:  started timer at: 2025-03-15T07:29:12.297


50
K : 8
[0 -1200 -100 -1200 -2000]
50
k : 8
1
-42326.98611740661
2396.0790122781304
50
K : 8
[0 -1600 -100 -1200 -2000]


[ Info:         4270.5252668s: 1 hour, 11 minutes, 10 seconds, 525 milliseconds
[ Info:  started timer at: 2025-03-15T08:40:22.912


50
k : 8
1
-46354.46024195153
2641.159171647851
50
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:          4383.191261s: 1 hour, 13 minutes, 3 seconds, 191 milliseconds
[ Info:  started timer at: 2025-03-15T09:53:26.194


50
k : 8
1
-49771.79793753768
2835.4908805275695
50
K : 8
[0 -2400 -100 -1200 -2000]


[ Info:         4420.0467386s: 1 hour, 13 minutes, 40 seconds, 46 milliseconds
[ Info:  started timer at: 2025-03-15T11:07:06.344


50
k : 8
1
-52719.9849091975
2981.376186858234
50
K : 8
[0 -2800 -100 -1200 -2000]


[ Info:          4727.951262s: 1 hour, 18 minutes, 47 seconds, 951 milliseconds
[ Info:  started timer at: 2025-03-15T12:25:54.406


50
k : 8
1
-55565.7827713778
3106.940559138487
50
K : 8
[0 -3200 -100 -1200 -2000]


[ Info:         4926.9465876s: 1 hour, 22 minutes, 6 seconds, 946 milliseconds
[ Info:  started timer at: 2025-03-15T13:48:01.466


50
k : 8
1
-58117.39083453047
3249.788602445001


[ Info:         4811.7121039s: 1 hour, 20 minutes, 11 seconds, 712 milliseconds


50
K : 10
[0 -800 -100 -1200 -2000]


[ Info:  started timer at: 2025-03-15T15:08:13.289


50
k : 10
1
-37331.48459055955
2046.2981713074491
50
K : 10
[0 -1200 -100 -1200 -2000]


[ Info:         7262.4268014s: 2 hours, 1 minute, 2 seconds, 426 milliseconds
[ Info:  started timer at: 2025-03-15T17:09:15.868


50
k : 10
1
-42317.93675391641
2386.2436676923007
50
K : 10
[0 -1600 -100 -1200 -2000]


[ Info:        10868.9009302s: 3 hours, 1 minute, 8 seconds, 900 milliseconds
[ Info:  started timer at: 2025-03-15T20:10:24.996


50
k : 10
1
-46198.309459510674
2634.710938663135
50
K : 10
[0 -2000 -100 -1200 -2000]


[ Info:         24121.603927s: 6 hours, 42 minutes, 1 second, 603 milliseconds
[ Info:  started timer at: 2025-03-16T02:52:27.096


50
k : 10
1
-49514.41678666861
2763.60317098978
50
K : 10
[0 -2400 -100 -1200 -2000]


[ Info:         4044.7623018s: 1 hour, 7 minutes, 24 seconds, 762 milliseconds
[ Info:  started timer at: 2025-03-16T03:59:51.944


50
k : 10
1
-52286.69623588115
2891.7747196018327
50
K : 10
[0 -2800 -100 -1200 -2000]


[ Info:         4102.4016111s: 1 hour, 8 minutes, 22 seconds, 401 milliseconds
[ Info:  started timer at: 2025-03-16T05:08:14.432


50
k : 10
1
-55074.33444443805
3037.0869267333264
50
K : 10
[0 -3200 -100 -1200 -2000]


[ Info:         4115.3897728s: 1 hour, 8 minutes, 35 seconds, 389 milliseconds
[ Info:  started timer at: 2025-03-16T06:16:49.909


50
k : 10
1
-57443.502662910534
3124.0881995006894
50
K : 12
[0 -800 -100 -1200 -2000]


[ Info:         4096.7971694s: 1 hour, 8 minutes, 16 seconds, 797 milliseconds
[ Info:  started timer at: 2025-03-16T07:25:06.793


50
k : 12
1
-37374.24328586959
2069.5016138165433
50
K : 12
[0 -1200 -100 -1200 -2000]


[ Info:         4134.7158672s: 1 hour, 8 minutes, 54 seconds, 715 milliseconds
[ Info:  started timer at: 2025-03-16T08:34:01.597


50
k : 12
1
-42261.71306957929
2379.443367947693
50
K : 12
[0 -1600 -100 -1200 -2000]


[ Info:          4088.622808s: 1 hour, 8 minutes, 8 seconds, 622 milliseconds
[ Info:  started timer at: 2025-03-16T09:42:10.305


50
k : 12
1
-46132.51558276075
2608.849023981574
50
K : 12
[0 -2000 -100 -1200 -2000]


[ Info:          4136.270328s: 1 hour, 8 minutes, 56 seconds, 270 milliseconds
[ Info:  started timer at: 2025-03-16T10:51:06.674


50
k : 12
1
-49439.11850941776
2765.924338902842
50
K : 12
[0 -2400 -100 -1200 -2000]


[ Info:         4158.6907655s: 1 hour, 9 minutes, 18 seconds, 690 milliseconds
[ Info:  started timer at: 2025-03-16T12:00:25.453


50
k : 12
1
-52165.56617094097
2855.863031950543
50
K : 12
[0 -2800 -100 -1200 -2000]


[ Info:         4104.7433789s: 1 hour, 8 minutes, 24 seconds, 743 milliseconds
[ Info:  started timer at: 2025-03-16T13:08:50.282


50
k : 12
1
-54844.22505390868
3007.9722740635143
50
K : 12
[0 -3200 -100 -1200 -2000]


[ Info:         4122.5114161s: 1 hour, 8 minutes, 42 seconds, 511 milliseconds
[ Info:  started timer at: 2025-03-16T14:17:32.880


50
k : 12
1
-57114.160324421784
3133.1871240610803
50
K : 14
[0 -800 -100 -1200 -2000]


[ Info:         4174.6756247s: 1 hour, 9 minutes, 34 seconds, 675 milliseconds
[ Info:  started timer at: 2025-03-16T15:27:07.645


50
k : 14
1
-37303.323808910216
2061.705700378244
50
K : 14
[0 -1200 -100 -1200 -2000]


[ Info:         4101.7789999s: 1 hour, 8 minutes, 21 seconds, 778 milliseconds
[ Info:  started timer at: 2025-03-16T16:35:29.510


50
k : 14
1
-42234.4387998846
2338.5302959968526
50
K : 14
[0 -1600 -100 -1200 -2000]


[ Info:         4103.3767027s: 1 hour, 8 minutes, 23 seconds, 376 milliseconds
[ Info:  started timer at: 2025-03-16T17:43:52.984


50
k : 14
1
-46140.309687699046
2638.0731670801692
50
K : 14
[0 -2000 -100 -1200 -2000]


[ Info:         4158.6396503s: 1 hour, 9 minutes, 18 seconds, 639 milliseconds
[ Info:  started timer at: 2025-03-16T18:53:11.723


50
k : 14
1
-49323.047269061404
2768.004052070224
50
K : 14
[0 -2400 -100 -1200 -2000]


[ Info:          4138.595289s: 1 hour, 8 minutes, 58 seconds, 595 milliseconds
[ Info:  started timer at: 2025-03-16T20:02:10.404


50
k : 14
1
-52135.96912103237
2886.2294882520055
50
K : 14
[0 -2800 -100 -1200 -2000]


[ Info:         4156.6602297s: 1 hour, 9 minutes, 16 seconds, 660 milliseconds
[ Info:  started timer at: 2025-03-16T21:11:27.152


50
k : 14
1
-54762.84060850906
2997.8993871009507
50
K : 14
[0 -3200 -100 -1200 -2000]


[ Info:         4168.1970294s: 1 hour, 9 minutes, 28 seconds, 197 milliseconds
[ Info:  started timer at: 2025-03-16T22:20:55.436


50
k : 14
1
-56926.734742354645
3065.003860642402
50
K : 16
[0 -800 -100 -1200 -2000]


[ Info:         4177.5528653s: 1 hour, 9 minutes, 37 seconds, 552 milliseconds
[ Info:  started timer at: 2025-03-16T23:30:33.077


50
k : 16
1
-37291.41748750791
2055.4798005936855
50
K : 16
[0 -1200 -100 -1200 -2000]


[ Info:         4084.3815408s: 1 hour, 8 minutes, 4 seconds, 381 milliseconds
[ Info:  started timer at: 2025-03-17T00:38:37.545


50
k : 16
1
-42221.17781808875
2378.081433611853
50
K : 16
[0 -1600 -100 -1200 -2000]


[ Info:         4137.3316481s: 1 hour, 8 minutes, 57 seconds, 331 milliseconds
[ Info:  started timer at: 2025-03-17T01:47:34.964


50
k : 16
1
-46092.40612052853
2586.7565736452066
50
K : 16
[0 -2000 -100 -1200 -2000]


[ Info:          4186.733892s: 1 hour, 9 minutes, 46 seconds, 733 milliseconds
[ Info:  started timer at: 2025-03-17T02:57:21.787


50
k : 16
1
-49383.433061645504
2755.151202193886
50
K : 16
[0 -2400 -100 -1200 -2000]


[ Info:         4125.7215039s: 1 hour, 8 minutes, 45 seconds, 721 milliseconds
[ Info:  started timer at: 2025-03-17T04:06:07.595


50
k : 16
1
-52014.875916339275
2831.9635068554066
50
K : 16
[0 -2800 -100 -1200 -2000]


[ Info:         4155.8957652s: 1 hour, 9 minutes, 15 seconds, 895 milliseconds
[ Info:  started timer at: 2025-03-17T05:15:23.578


50
k : 16
1
-54598.97033188022
2962.255072028944
50
K : 16
[0 -3200 -100 -1200 -2000]


[ Info:         4176.3317324s: 1 hour, 9 minutes, 36 seconds, 331 milliseconds
[ Info:  started timer at: 2025-03-17T06:24:59.999


50
k : 16
1
-56838.86843048513
3062.773709354868
50
K : 18
[0 -800 -100 -1200 -2000]


[ Info:         4201.1723875s: 1 hour, 10 minutes, 1 second, 172 milliseconds
[ Info:  started timer at: 2025-03-17T07:35:01.259


50
k : 18
1
-37307.99919202522
2052.1241293208213
50
K : 18
[0 -1200 -100 -1200 -2000]


[ Info:         4169.6933407s: 1 hour, 9 minutes, 29 seconds, 693 milliseconds
[ Info:  started timer at: 2025-03-17T08:44:31.041


50
k : 18
1
-42207.82094012489
2396.1161969515683
50
K : 18
[0 -1600 -100 -1200 -2000]


[ Info:         4151.9068878s: 1 hour, 9 minutes, 11 seconds, 906 milliseconds
[ Info:  started timer at: 2025-03-17T09:53:43.035


50
k : 18
1
-46063.703780034986
2611.408167019467
50
K : 18
[0 -2000 -100 -1200 -2000]


[ Info:         4212.8416371s: 1 hour, 10 minutes, 12 seconds, 841 milliseconds
[ Info:  started timer at: 2025-03-17T11:03:55.965


50
k : 18
1
-49324.91615720272
2753.6447540713057
50
K : 18
[0 -2400 -100 -1200 -2000]


[ Info:          4175.791814s: 1 hour, 9 minutes, 35 seconds, 791 milliseconds
[ Info:  started timer at: 2025-03-17T12:13:31.845


50
k : 18
1
-52142.0975764871
2893.5540172895144
50
K : 18
[0 -2800 -100 -1200 -2000]


[ Info:          4244.641525s: 1 hour, 10 minutes, 44 seconds, 641 milliseconds
[ Info:  started timer at: 2025-03-17T13:24:16.575


50
k : 18
1
-54566.112390273476
2943.414226459189
50
K : 18
[0 -3200 -100 -1200 -2000]


[ Info:         4224.5251217s: 1 hour, 10 minutes, 24 seconds, 525 milliseconds
[ Info:  started timer at: 2025-03-17T14:34:41.189


50
k : 18
1
-56812.253924733996
3087.398400256235
50
K : 20
[0 -800 -100 -1200 -2000]


[ Info:         4232.2469549s: 1 hour, 10 minutes, 32 seconds, 246 milliseconds
[ Info:  started timer at: 2025-03-17T15:45:13.526


50
k : 20
1
-37287.31291593523
2070.8891075138267
50
K : 20
[0 -1200 -100 -1200 -2000]


[ Info:         4215.5774788s: 1 hour, 10 minutes, 15 seconds, 577 milliseconds
[ Info:  started timer at: 2025-03-17T16:55:29.192


50
k : 20
1
-42140.19210349226
2410.909012770536
50
K : 20
[0 -1600 -100 -1200 -2000]


[ Info:         4230.0822903s: 1 hour, 10 minutes, 30 seconds, 82 milliseconds
[ Info:  started timer at: 2025-03-17T18:05:59.362


50
k : 20
1
-46002.74843627559
2674.959370413973
50
K : 20
[0 -2000 -100 -1200 -2000]


[ Info:         4273.8355533s: 1 hour, 11 minutes, 13 seconds, 835 milliseconds
[ Info:  started timer at: 2025-03-17T19:17:13.287


50
k : 20
1
-49285.59612691146
2818.3960817459106
50
K : 20
[0 -2400 -100 -1200 -2000]


[ Info:         4257.8103463s: 1 hour, 10 minutes, 57 seconds, 810 milliseconds
[ Info:  started timer at: 2025-03-17T20:28:11.186


50
k : 20
1
-52157.46137809317
3024.974667545439
50
K : 20
[0 -2800 -100 -1200 -2000]


[ Info:         4260.7198916s: 1 hour, 11 minutes, 719 milliseconds
[ Info:  started timer at: 2025-03-17T21:39:11.995


50
k : 20
1
-55157.65180088837
3233.215318596839
50
K : 20
[0 -3200 -100 -1200 -2000]


[ Info:         4285.9296032s: 1 hour, 11 minutes, 25 seconds, 929 milliseconds
[ Info:  started timer at: 2025-03-17T22:50:38.015


50
k : 20
1
-58515.86999265702
3711.2501895216724
50
K : 22
[0 -800 -100 -1200 -2000]


[ Info:         4310.3503165s: 1 hour, 11 minutes, 50 seconds, 350 milliseconds
[ Info:  started timer at: 2025-03-18T00:02:28.457


50
k : 22
1
-37304.56102709558
2168.9193955954024
50
K : 22
[0 -1200 -100 -1200 -2000]


[ Info:         4244.9144481s: 1 hour, 10 minutes, 44 seconds, 914 milliseconds
[ Info:  started timer at: 2025-03-18T01:13:13.461


50
k : 22
1
-42246.62013652837
2525.454808405117
50
K : 22
[0 -1600 -100 -1200 -2000]


[ Info:          4222.094239s: 1 hour, 10 minutes, 22 seconds, 94 milliseconds
[ Info:  started timer at: 2025-03-18T02:23:35.645


50
k : 22
1
-46343.51436559007
2849.9683530539232
50
K : 22
[0 -2000 -100 -1200 -2000]


[ Info:          4241.582869s: 1 hour, 10 minutes, 41 seconds, 582 milliseconds
[ Info:  started timer at: 2025-03-18T03:34:17.317


50
k : 22
1
-50433.915702335995
3342.055793119871
50
K : 22
[0 -2400 -100 -1200 -2000]


[ Info:         4268.8214367s: 1 hour, 11 minutes, 8 seconds, 821 milliseconds
[ Info:  started timer at: 2025-03-18T04:45:26.228


50
k : 22
1
-55417.196814625655
3932.975890135496
50
K : 22
[0 -2800 -100 -1200 -2000]


[ Info:          4207.513215s: 1 hour, 10 minutes, 7 seconds, 513 milliseconds
[ Info:  started timer at: 2025-03-18T05:55:33.829


50
k : 22
1
-60748.50599517405
4398.635859506943
50
K : 22
[0 -3200 -100 -1200 -2000]


[ Info:         4259.3735055s: 1 hour, 10 minutes, 59 seconds, 373 milliseconds
[ Info:  started timer at: 2025-03-18T07:06:33.292


50
k : 22
1
-65400.56576300217
4675.0887027191
50
K : 24
[0 -800 -100 -1200 -2000]


[ Info:         4252.4990841s: 1 hour, 10 minutes, 52 seconds, 499 milliseconds
[ Info:  started timer at: 2025-03-18T08:17:25.881


50
k : 24
1
-37780.800657625594
2519.5590374173926
50
K : 24
[0 -1200 -100 -1200 -2000]


[ Info:         4247.7638977s: 1 hour, 10 minutes, 47 seconds, 763 milliseconds
[ Info:  started timer at: 2025-03-18T09:28:13.735


50
k : 24
1
-43940.53126801116
3332.7368102061137
50
K : 24
[0 -1600 -100 -1200 -2000]


[ Info:         4188.3792261s: 1 hour, 9 minutes, 48 seconds, 379 milliseconds
[ Info:  started timer at: 2025-03-18T10:38:02.202


50
k : 24
1
-50789.451716644006
4203.343666303945
50
K : 24
[0 -2000 -100 -1200 -2000]


[ Info:          4195.743455s: 1 hour, 9 minutes, 55 seconds, 743 milliseconds
[ Info:  started timer at: 2025-03-18T11:47:58.035


50
k : 24
1
-57403.56722065035
4593.49047965897


[ Info:         4268.3245716s: 1 hour, 11 minutes, 8 seconds, 324 milliseconds


50
K : 24
[0 -2400 -100 -1200 -2000]


[ Info:  started timer at: 2025-03-18T12:59:06.460


50
k : 24
1
-62850.56196246575
4774.717758214307
50
K : 24
[0 -2800 -100 -1200 -2000]


[ Info:         4257.0369718s: 1 hour, 10 minutes, 57 seconds, 36 milliseconds
[ Info:  started timer at: 2025-03-18T14:10:03.587


50
k : 24
1
-66393.51233704669
4728.182314587592
50
K : 24
[0 -3200 -100 -1200 -2000]


[ Info:         4203.1625096s: 1 hour, 10 minutes, 3 seconds, 162 milliseconds
[ Info:  started timer at: 2025-03-18T15:20:06.848


50
k : 24
1
-68724.74001917618
4769.6698412985825
60
K : 2
[0 -800 -100 -1200 -2000]


[ Info:         4247.5820573s: 1 hour, 10 minutes, 47 seconds, 582 milliseconds
[ Info:  started timer at: 2025-03-18T16:30:54.519


60
k : 2
1
-44770.775699313934
2981.3466000829735
60
K : 2
[0 -1200 -100 -1200 -2000]


[ Info:         5131.6376397s: 1 hour, 25 minutes, 31 seconds, 637 milliseconds
[ Info:  started timer at: 2025-03-18T17:56:26.265


60
k : 2
1
-52758.32040369431
3537.74323317038
60
K : 2
[0 -1600 -100 -1200 -2000]


[ Info:         5073.5646384s: 1 hour, 24 minutes, 33 seconds, 564 milliseconds
[ Info:  started timer at: 2025-03-18T19:20:59.936


60
k : 2
1
-59890.49524130011
3982.63580164052
60
K : 2
[0 -2000 -100 -1200 -2000]


[ Info:         4989.2969449s: 1 hour, 23 minutes, 9 seconds, 296 milliseconds
[ Info:  started timer at: 2025-03-18T20:44:09.339


60
k : 2
1
-65845.13940209206
4330.410259718691
60
K : 2
[0 -2400 -100 -1200 -2000]


[ Info:         5031.9755349s: 1 hour, 23 minutes, 51 seconds, 975 milliseconds
[ Info:  started timer at: 2025-03-18T22:08:01.420


60
k : 2
1
-70380.61302409407
4529.967683907143
60
K : 2
[0 -2800 -100 -1200 -2000]


[ Info:         5078.0189926s: 1 hour, 24 minutes, 38 seconds, 18 milliseconds
[ Info:  started timer at: 2025-03-18T23:32:39.546


60
k : 2
1
-74027.68318496311
4580.456283923574
60
K : 2
[0 -3200 -100 -1200 -2000]


[ Info:         5032.0486445s: 1 hour, 23 minutes, 52 seconds, 48 milliseconds
[ Info:  started timer at: 2025-03-19T00:56:31.700


60
k : 2
1
-77541.59209538395
4670.462013405407
60
K : 4
[0 -800 -100 -1200 -2000]


[ Info:         5055.8685474s: 1 hour, 24 minutes, 15 seconds, 868 milliseconds
[ Info:  started timer at: 2025-03-19T02:20:47.675


60
k : 4
1
-41402.40725435661
2160.122322228073
60
K : 4
[0 -1200 -100 -1200 -2000]


[ Info:         5030.7189889s: 1 hour, 23 minutes, 50 seconds, 718 milliseconds
[ Info:  started timer at: 2025-03-19T03:44:38.501


60
k : 4
1
-47687.97831372302
2670.0430712344228
60
K : 4
[0 -1600 -100 -1200 -2000]


[ Info:         5100.5393007s: 1 hour, 25 minutes, 539 milliseconds
[ Info:  started timer at: 2025-03-19T05:09:39.147


60
k : 4
1
-53173.32090120977
3156.1313312007965
60
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:         5067.6565292s: 1 hour, 24 minutes, 27 seconds, 656 milliseconds
[ Info:  started timer at: 2025-03-19T06:34:06.910


60
k : 4
1
-57906.32237163122
3540.062976260419
60
K : 4
[0 -2400 -100 -1200 -2000]


[ Info:          5067.601253s: 1 hour, 24 minutes, 27 seconds, 601 milliseconds
[ Info:  started timer at: 2025-03-19T07:58:34.619


60
k : 4
1
-61897.85971467748
3706.156808755398
60
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:         5102.7361667s: 1 hour, 25 minutes, 2 seconds, 736 milliseconds
[ Info:  started timer at: 2025-03-19T09:23:37.463


In [ ]:
df

In [ ]:
using CSV
CSV.write("Hetero CW-POMDP.csv", df)