In [1]:
# import Pkg;
# Pkg.add("POMDPSimulators")
# Pkg.add("POMDPs")
# Pkg.add("POMDPTools")
# Pkg.add("QuickPOMDPs")
# Pkg.add("MCTS")
# Pkg.add("DiscreteValueIteration")
# Pkg.add("POMDPModels")
# Pkg.add("POMDPPolicies")
# Pkg.add("Distributions")
# Pkg.add("Combinatorics")
# Pkg.add("StaticArrays")
# Pkg.add("D3Trees")
# Pkg.add("Random")
# Pkg.add("FileIO")
# Pkg.add("JLD2")
# Pkg.add("TickTock")



In [2]:
# import Pkg; Pkg.add("DataFrames")

In [3]:
using POMDPs, POMDPTools, QuickPOMDPs, MCTS, DiscreteValueIteration, POMDPSimulators, POMDPModels, POMDPPolicies, POMDPModelTools
using Distributions, Combinatorics, StaticArrays, D3Trees, Random
using FileIO, JLD2, TickTock

In [4]:
global Number_level = 4;
global Action_num = 4;
gamma=0.95

States=Array((1:Number_level))
Observations=Array((1:Number_level))

4-element Vector{Int64}:
 1
 2
 3
 4

In [5]:
Observation_matrix=[
    0.8 0.2 0.0 0.0;
    0.1 0.8 0.1 0.0;
    0.0 0.2 0.8 0.0;
    0.0 0.0 0.0 1.0
]

4×4 Matrix{Float64}:
 0.8  0.2  0.0  0.0
 0.1  0.8  0.1  0.0
 0.0  0.2  0.8  0.0
 0.0  0.0  0.0  1.0

In [6]:
T=zeros(Number_level,Number_level,3,100);

# Load transition probability matrix for each component
for i in 1:100
    fullname = "C:/Users/hhu98/OneDrive - UW-Madison/POMDP/code/Heterogeneous system/hetero_tm/tm"*string(i);
   
    Transition_matrix = load(fullname*".jld2","transition_matrix");
    # the last term in argument of T, which is written as 'i' here,
    # is the index of component in the heterogeneous system
    T[:,:,1,i].=Transition_matrix; # a=1: do not replace
    T[:,:,2,i].=Transition_matrix; # a=2: corrective replacement
    for j in 1:Number_level
        T[j,:,3,i].=Transition_matrix[1,:]; # a=3: preventive replacement
        end
    # T[Number_level,:,1,i].=Transition_matrix[1,:]
    T[Number_level,:,1,i].=0.0
    T[Number_level,Number_level,1,i]=1.0
    T[Number_level,:,2,i].=Transition_matrix[1,:]

end

┌ Warning: This file was written in a newer version of the JLD2 file format.
│ Please consider updating JLD2.
└ @ JLD2 C:\Users\hhu98\.julia\packages\JLD2\VWinU\src\file_header.jl:39
┌ Warning: This file was written with a different version of JLD2 that may not be compatible.
│ Attempting to load data.
└ @ JLD2 C:\Users\hhu98\.julia\packages\JLD2\VWinU\src\file_header.jl:43


In [7]:
NumberUnits=20
limit=12
failure_penalty = -1200.0;
maintenance_penalty = -100.0;
setup_cost = -300.0;
normal_operation = 0.0;
system_penalty=-2000

-2000

In [8]:
SparseCat(Observations, Observation_matrix[1,:])

               SparseCat distribution           
     ┌                                        ┐ 
   1 ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 0.8   
   2 ┤■■■■■■■■■ 0.2                             
   3 ┤ 0.0                                      
   4 ┤ 0.0                                      
     └                                        ┘ 

In [ ]:
Initialstates = zeros(Number_level)
Initialstates[1]=1.0
Initialstates
Initialstate = SparseCat(States, Initialstates)

Initialobs = SparseCat(Observations, Observation_matrix[1,:])

4-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0

In [12]:
function create_pomdps()

    Unit_pomdps = Dict{Int,POMDP}()
    
    for i in 1:NumberUnits
    
     Unit_pomdps[i]= QuickPOMDP(
        states=States,
        actions=Array((1:Action_num)),
        observations = Observations,
        initialstate = Initialstate,
        initialobs = Initialobs,
        discount = gamma,
    
        transition = function(s,a)
            if a == 1 # NO REPAIR, NO SYSTEM FAILURE
                return SparseCat(States, T[s,:,1,i])
            end
            if a == 2 # UNIT NOT REPAIRED UNLESS FAILURE BUT REPAIR IN SYSTEM
                if s == Number_level
                    s = 1
                    return SparseCat(States, T[s,:,2,i])
                else
                    return SparseCat(States, T[s,:,2,i])
                end
            end
            if a == 3 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM, NO SYSTEM FAILURE
                if s==Number_level
                    s=1
                    return SparseCat(States, T[s,:,3,i])
                else
                    s = 1
                    return SparseCat(States, T[s,:,3,i])
                end
            end
            if a == 4 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM,SYSTEM FAILED
                if s==Number_level
                    s=1
                    return SparseCat(States, T[s,:,3,i])
                else
                    s = 1
                    return SparseCat(States, T[s,:,3,i])
                end
            end
        end,
    
        observation = function(a,s)
            return SparseCat(Observations, Observation_matrix[s,:])
        end,
            
        reward = function (s, a)
            if a == 1 # NO REPAIR, NO SYSTEM FAILURE
                if s == Number_level
                    return system_penalty/(limit)
                else
                    return normal_operation
                end
            end
            if a == 2 # UNIT NOT REPAIRED UNLESS FAILURE BUT REPAIR IN SYSTEM, NO SYSTEM FAILURE PENALTY
                if s == Number_level
                    return failure_penalty +  setup_cost/NumberUnits + normal_operation
                else
                    # Here it doesn't matter whether systems fails or not, since C_b does not apply to functional units
                    return normal_operation +  setup_cost/NumberUnits
                end
            end
            if a == 3 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM, NO SYSTEM FAILURE PENALTY
                if s==Number_level
                    return failure_penalty +  setup_cost/NumberUnits + normal_operation
                else
                    # Here it doesn't matter whether systems fails or not, since C_b does not apply to functional units
                    return maintenance_penalty +  setup_cost/NumberUnits+ normal_operation 
                end
            end
            if a == 4 # UNIT REPAIRED AND MAINTENANCE IN SYSTEM,SYSTEM FAILED
                if s==Number_level
                    return failure_penalty +  setup_cost/NumberUnits + normal_operation + system_penalty/(limit)
                else
                    return maintenance_penalty +  setup_cost/NumberUnits + normal_operation
                end
            end
        end,
        
    )
    end
    return Unit_pomdps
    end

create_pomdps (generic function with 1 method)

In [13]:
function generative(s,a,i,rng=23) # calculate TRUE COMPONENT-LEVEL reward r_i(s_i,a_i) and get evolving states
    if a==1 # No maintenance in the system, no system failure
        crd=Categorical(T[s,:,1,i])
        s=rand(crd)
        r=normal_operation
        obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
        obs = rand(obs_distribution)
        return (sp=s,r=r,o=obs)
    end

    if a==2 # Maintenance occurs in the system, no system failure, corrective maintenance for the unit
        if s==Number_level
            crd=Categorical(T[1,:,2,i])
            s=rand(crd)
            r=failure_penalty  + normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        else
            crd = Categorical(T[s,:,2,i])
            s = rand(crd)
            r = normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        end
    end

    if a==3 # Maintenance occurs in the system, no system failure, preventive maintenance for the unit
        if s==Number_level
            crd=Categorical(T[1,:,3,i])
            s=rand(crd)
            r=failure_penalty  + normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        else
            crd = Categorical(T[s,:,3,i])
            s = rand(crd)
            r = maintenance_penalty+normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        end
    end

    if a==4 # maintenance in system, system failure occurs, preventive replacement for the unit
        if s==Number_level
            crd = Categorical(T[1,:,3,i])
            s = rand(crd)
            r=failure_penalty+ normal_operation
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        else
            r = maintenance_penalty+normal_operation
            crd = Categorical(T[1,:,3,i])
            s = rand(crd)
            obs_distribution = SparseCat(Observations, Observation_matrix[s,:])
            obs = rand(obs_distribution)
            return (sp=s,r=r,o=obs)
        end
    end
end

        
        
    

generative (generic function with 2 methods)

#### Belief updater

$$b'(s_j)=P(s_j\vert o,a,b)=\dfrac{P(o\vert s_j,a)\sum_{s_i\in \mathcal{S}}P(s_j\vert s_i,a)b(s_i)}{\sum_{s_j\in \mathcal{S}}P(o\vert s_j,a)\sum_{s_i\in \mathcal{S}}P(s_j\vert s_i,a)b(s_i)}$$

In [14]:
# Input: prior belief, action, observation, index of the component
# Output: updated belief of the component
function update_belief(b,a,o,i) 
    # NOTE: 
    # in input, b is belief from last epoch (before a)
    # a is the last action we took
    # o is the new observation after a
    pomdp = Unit_pomdps[i]
    updated_belief = zeros(length(b))
    if o==4
        updated_belief[Number_level]=1.0
        return updated_belief
    end

    if (a==3) ||(a==4)
    # We assume perfect maintenance and it is know to decision maker(belief updater)
        for sp in 1: Number_level
            p_obs = Observation_matrix[sp,o]
            p_trans = pdf(transition(pomdp,1,1),sp) 
            updated_belief[sp] = p_obs * p_trans
        end
        updated_belief ./= sum(updated_belief)
        return updated_belief
    end
    
    for sp in 1:length(states(pomdp)) 
        # p_observation = POMDPs.observation(pomdp,a,sp) 
        # p_obs = pdf(p_observation,o)
        p_obs = Observation_matrix[sp,o]
        p_trans = 0.0
        for s in 1:length(states(pomdp))
            #trans = transition(pomdp, s,a)
            #p_trans += pdf(transition(pomdp, s,a),sp) * pdf(b, s)
            # p_trans += T[s,sp,a] * pdf(b, s)
            # p_trans += T[s,sp,a,i] * b[s]
            p_trans += pdf(transition(pomdp,s,a),sp) * b[s]
        end
        updated_belief[sp] = p_obs * p_trans
    end
        # Normalize the updated belief state to ensure it sums up to 1
        updated_belief ./= sum(updated_belief)
    return updated_belief
end


update_belief (generic function with 1 method)

### Value Iteration

In [15]:
function ValueIteration(γ)
    # Here we always consider the state with the highest belief as the true state
    Q = zeros((Number_level, 4, NumberUnits))
    V = zeros(Float64, (Number_level, NumberUnits)).+1000
    for k in 1:NumberUnits
        for i in 1:10000
            for s in 1:Number_level
                Threads.@threads for a in 1:4
                    if a == 4
                        Q[s,a,k] = (reward(Unit_pomdps[k],s,a)) + γ*(sum(T[s,s1,3,k]*V[s1,k] for s1 in 1:Number_level))
                    else
                    Q[s,a,k] = (reward(Unit_pomdps[k],s,a)) + γ*(sum(T[s,s1,a,k]*V[s1,k] for s1 in 1:Number_level))
                    end
                end
                V[s,k] = findmax(Q[s, 1:4, k])[1]
            end
        end
    end
    return Q
end

ValueIteration (generic function with 1 method)

### System-level decision making

In [16]:
function decision(o, b)
    a_final = repeat(1:1,NumberUnits)
    # Instead of using maximum likelihood state,
    # we use belief-weighted sum of Q function

    failed_components = 0
    for i in 1:NumberUnits # numerate over units
        if o[i] == Number_level # failure state is self-announcing
            failed_components+=1
        end
    end

    # calculate belief-based Q table for each unit
    Q_belief = zeros((NumberUnits, 4))
    
    for i in 1:NumberUnits
        belief = b[i]
        for a in 1:4
            Q_belief[i,a] = sum(belief[s] * Q[s,a,i] for s in 1:Number_level)
        end
    end

    # decision making: 3 scenarios
    # 1) System fails
    if failed_components >= limit
        for i in 1:NumberUnits
            a_final[i]=argmax(a->Q_belief[i,a],[2,3])
            if o[i] == Number_level
                a_final[i]=4
            end
        end
        return a_final
    end

    q0 = 0.0
    a0 = repeat(1:1, NumberUnits)
    for i in 1:NumberUnits
        q0+=Q_belief[i,1]
    end

    q1 = 0.0
    a1 = repeat(1:1, NumberUnits)
    for i in 1:NumberUnits
        a1[i] = argmax(a->Q_belief[i,a], [2,3])
        if o[i] == Number_level
            a1[i] = 3
        end
        q1 += Q_belief[i, a1[i]]
    end

    if !(3 in a1)
        a1 = a0
        q1 = q0
    end

    if q0 > q1
        return a0
    else
        return a1
    end
end
    



decision (generic function with 1 method)

### Iteration

In [17]:
using DataFrames
df= DataFrame(u=[],K=[],n=[],s=[],m=[],f=[],p=[],lamb=[],mean=[],std=[])

cost=[ 
    [0	-1200	-100	-1200 -2000],
    [0	-2000	-100	-1200 -2000],
    [0  -2800   -100    -1200 -2000]
] 


for units in [20, 30, 40]

    for K in 4:4:convert(Int64, floor((units+1)/2))  

    global NumberUnits=convert(Int64,units)
    global limit=convert(Int64,K)
    #for lambda in [1,0.9,0.75,0.5,0.1,0.075,0.05,0.01,0.0075,0.005,0.0001]
    for lambda in 1:1:1
    global lamb=lambda
    for c in cost
        tick()
        println(units)  
        print("K : ")
        println(K)
        global normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty=c
        println(c)  
        global NumberUnits=units

# POMDPs are defined
global Unit_pomdps = create_pomdps()
# CONTINUE to obtain TRIVIAL SOLUTION and compute expected total rewards

# Obtain Q function using Value Iteration, same as CW-MDP
global Q = ValueIteration(gamma)
println(isnan(Q[1,1,1]))
if sum(isnan(Q[1,1,1])) > 0.0
    continue
end

tick()

trials=10000;
simsteps = 100;
results=zeros(trials)*0.1
Threads.@threads  for h in 1:trials
    s=repeat(1:1,NumberUnits)
    o = rand(Initialobs, NumberUnits)
    belief = [Observation_matrix[1,:] for j in 1:NumberUnits]
    R_sequence=[] 
    r=repeat(1:1,NumberUnits)*1.0

    # iteration
    for k in 1:simsteps
        a=decision(o,belief) # system-level decision making: action vector
        # SANITY CHECK
        # Update belief for each component individually
        #b=update_belief(b, a, o, multiunit) # what is the sequence of observing, updating belief, taking action?
        
        R_instant = 0.0
        global failed_components=0
        # When generating new state and new reward, we use true states
        for i in 1:NumberUnits # numerate over units
            if o[i]==Number_level # failure state is self-announcing
                failed_components+=1
            end
            s[i],r[i],o[i]=generative(s[i],a[i],i,234) #call generative function for underlying states
            # it might be better to use generative function to give o as well
            # o[i]=emission(s[i]) # observation generated by new underlying state
            belief[i]=update_belief(belief[i], a[i], o[i], i)
            # sum up single-component cost
            R_instant += r[i]
        end
        # add setup cost
        if (2 in a) ||(3 in a) ||(4 in a)
            R_instant += setup_cost
        end
        # add system failure penalty
        if failed_components >= limit
            R_instant += system_penalty
        end
        # record instant reward of current time step
        append!(R_sequence, R_instant)

    end
    R_discounted=0
    for k in 1:simsteps
        R_discounted=gamma * R_discounted+R_sequence[simsteps-k+1]
    end
    results[h]=R_discounted
end # end the 10000 trials

println(units)
            print("k : ")
            println(limit)
println(lambda)

println(mean(results))

println(std(results))
pushfirst!(df,[units,limit,normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty,lamb,mean(results),std(results)])
        
tock()

                    
                    
    end
    end        
end
end


20
K : 4


[ Info:  started timer at: 2025-03-07T16:08:28.324


[0 -1200 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-03-07T16:08:52.118


20
k : 4
1
-22148.67686171796
2117.485180883976
20
K : 4
[0 -2000 -100 -1200 -2000]


[ Info:          666.9809666s: 11 minutes, 6 seconds, 980 milliseconds
[ Info:  started timer at: 2025-03-07T16:19:59.233


false


[ Info:  started timer at: 2025-03-07T16:20:21.301


20
k : 4
1
-27007.895859104163
2513.236586628227
20
K : 4
[0 -2800 -100 -1200 -2000]

[ Info:            662.28049s: 11 minutes, 2 seconds, 280 milliseconds
[ Info:  started timer at: 2025-03-07T16:31:23.581



false


[ Info:  started timer at: 2025-03-07T16:31:45.575


20
k : 4
1
-31381.1846569338
2912.3967034429816
20
K : 8
[0 -1200 -100 -1200 -2000]

[ Info:          218.7065062s: 3 minutes, 38 seconds, 706 milliseconds
[ Info:  started timer at: 2025-03-07T16:35:24.282



false


[ Info:  started timer at: 2025-03-07T16:35:46.446


20
k : 8
1
-21259.325417501397
1952.6829884596339
20
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:          219.6092724s: 3 minutes, 39 seconds, 609 milliseconds
[ Info:  started timer at: 2025-03-07T16:39:26.055


false


[ Info:  started timer at: 2025-03-07T16:39:48.397


20
k : 8
1
-25170.037219984628
2166.3892183957305
20
K : 8
[0 -2800 -100 -1200 -2000]


[ Info:          218.4507179s: 3 minutes, 38 seconds, 450 milliseconds
[ Info:  started timer at: 2025-03-07T16:43:26.848


false


[ Info:  started timer at: 2025-03-07T16:43:49.381


20
k : 8
1
-28376.584594968568
2444.915293417958
30
K : 4
[0 -1200 -100 -1200 -2000]

[ Info:          213.9833132s: 3 minutes, 33 seconds, 983 milliseconds
[ Info:  started timer at: 2025-03-07T16:47:23.375



false


[ Info:  started timer at: 2025-03-07T16:47:57.185


30
k : 4
1
-31723.531874456716
2436.3771063876343


[ Info:           317.489733s: 5 minutes, 17 seconds, 489 milliseconds
[ Info:  started timer at: 2025-03-07T16:53:14.686


30
K : 4
[0 -2000 -100 -1200 -2000]
false


[ Info:  started timer at: 2025-03-07T16:53:51.082


30
k : 4
1
-38282.853020771574
2928.1592019811733
30
K : 4
[0 -2800 -100 -1200 -2000]


[ Info:          313.3251507s: 5 minutes, 13 seconds, 325 milliseconds
[ Info:  started timer at: 2025-03-07T16:59:04.406


false


[ Info:  started timer at: 2025-03-07T16:59:39.832


30
k : 4
1
-43952.8314917599
3370.726458135399
30
K : 8
[0 -1200 -100 -1200 -2000]


[ Info:          312.3416721s: 5 minutes, 12 seconds, 341 milliseconds
[ Info:  started timer at: 2025-03-07T17:04:52.174


false


[ Info:  started timer at: 2025-03-07T17:05:27.074


30
k : 8
1
-30769.47666456793
2231.1630370785088
30
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:          317.2280251s: 5 minutes, 17 seconds, 228 milliseconds
[ Info:  started timer at: 2025-03-07T17:10:44.302


false


[ Info:  started timer at: 2025-03-07T17:11:21.106


30
k : 8
1
-36131.04202219548
2532.7103935511354
30
K : 8
[0 -2800 -100 -1200 -2000]

[ Info:           314.366747s: 5 minutes, 14 seconds, 366 milliseconds
[ Info:  started timer at: 2025-03-07T17:16:35.472



false


[ Info:  started timer at: 2025-03-07T17:17:11.256


30
k : 8
1
-40556.02811912899
2829.508241651391
30
K : 12
[0 -1200 -100 -1200 -2000]

[ Info:          309.7382989s: 5 minutes, 9 seconds, 738 milliseconds
[ Info:  started timer at: 2025-03-07T17:22:21.006



false


[ Info:  started timer at: 2025-03-07T17:22:56.228


30
k : 12
1
-30618.402812482764
2228.156674414003
30
K : 12
[0 -2000 -100 -1200 -2000]


[ Info:          311.1922792s: 5 minutes, 11 seconds, 192 milliseconds
[ Info:  started timer at: 2025-03-07T17:28:07.421


false


[ Info:  started timer at: 2025-03-07T17:28:42.830


30
k : 12
1
-35774.05515988812
2511.705953477097
30
K : 12
[0 -2800 -100 -1200 -2000]


[ Info:          317.0153551s: 5 minutes, 17 seconds, 15 milliseconds
[ Info:  started timer at: 2025-03-07T17:33:59.845


false


[ Info:  started timer at: 2025-03-07T17:34:36.883


30
k : 12
1
-39759.895575442184
2686.1939388348646
40
K : 4
[0 -1200 -100 -1200 -2000]


[ Info:          310.6329481s: 5 minutes, 10 seconds, 632 milliseconds
[ Info:  started timer at: 2025-03-07T17:39:47.527


false


[ Info:  started timer at: 2025-03-07T17:40:36.760


40
k : 4
1
-37250.727410278705
2612.9169032490686
40
K : 4
[0 -2000 -100 -1200 -2000]

[ Info:          427.4958864s: 7 minutes, 7 seconds, 495 milliseconds
[ Info:  started timer at: 2025-03-07T17:47:44.267



false


[ Info:  started timer at: 2025-03-07T17:48:34.960


40
k : 4
1
-44831.475181215385
3205.2706790370858
40
K : 4
[0 -2800 -100 -1200 -2000]

[ Info:          422.6882742s: 7 minutes, 2 seconds, 688 milliseconds
[ Info:  started timer at: 2025-03-07T17:55:37.648



false


[ Info:  started timer at: 2025-03-07T17:56:27.091


40
k : 4
1
-51171.20534967889
3621.127386174171
40
K : 8
[0 -1200 -100 -1200 -2000]


[ Info:          422.3112886s: 7 minutes, 2 seconds, 311 milliseconds
[ Info:  started timer at: 2025-03-07T18:03:29.402


false


[ Info:  started timer at: 2025-03-07T18:04:19.197


40
k : 8
1
-36211.390084337785
2371.182063235338
40
K : 8
[0 -2000 -100 -1200 -2000]


[ Info:          423.5217977s: 7 minutes, 3 seconds, 521 milliseconds
[ Info:  started timer at: 2025-03-07T18:11:22.719


false


[ Info:  started timer at: 2025-03-07T18:12:09.840


40
k : 8
1
-42572.16408647531
2741.858429381067
40
K : 8
[0 -2800 -100 -1200 -2000]

[ Info:           420.753977s: 7 minutes, 753 milliseconds
[ Info:  started timer at: 2025-03-07T18:19:10.605



false


[ Info:  started timer at: 2025-03-07T18:20:00.477


40
k : 8
1
-47662.209963405556
3037.401183702456
40
K : 12
[0 -1200 -100 -1200 -2000]


[ Info:          417.1862796s: 6 minutes, 57 seconds, 186 milliseconds
[ Info:  started timer at: 2025-03-07T18:26:57.663


false


[ Info:  started timer at: 2025-03-07T18:27:46.790


40
k : 12
1
-36063.891950085985
2362.7872903762027
40
K : 12
[0 -2000 -100 -1200 -2000]


[ Info:          421.6764285s: 7 minutes, 1 second, 676 milliseconds
[ Info:  started timer at: 2025-03-07T18:34:48.477


false


[ Info:  started timer at: 2025-03-07T18:35:38.395


40
k : 12
1
-42161.56516739368
2719.475015501155
40
K : 12
[0 -2800 -100 -1200 -2000]


[ Info:          420.3819106s: 7 minutes, 381 milliseconds
[ Info:  started timer at: 2025-03-07T18:42:38.777


false


[ Info:  started timer at: 2025-03-07T18:43:28.061


40
k : 12
1
-46874.187268742106
2907.7524396609388
40
K : 16
[0 -1200 -100 -1200 -2000]

[ Info:          418.4269589s: 6 minutes, 58 seconds, 426 milliseconds
[ Info:  started timer at: 2025-03-07T18:50:26.488



false


[ Info:  started timer at: 2025-03-07T18:51:15.922


40
k : 16
1
-36032.76113200546
2357.1770491784137
40
K : 16
[0 -2000 -100 -1200 -2000]

[ Info:          421.8182351s: 7 minutes, 1 second, 818 milliseconds
[ Info:  started timer at: 2025-03-07T18:58:17.752



false


[ Info:  started timer at: 2025-03-07T18:59:07.172


40
k : 16
1
-42014.83614307723
2681.3274394785462
40
K : 16
[0 -2800 -100 -1200 -2000]


[ Info:          419.7404711s: 6 minutes, 59 seconds, 740 milliseconds
[ Info:  started timer at: 2025-03-07T19:06:06.923


false


[ Info:  started timer at: 2025-03-07T19:06:53.781


40
k : 16
1
-46520.88401872413
2875.0006193826816
40
K : 20
[0 -1200 -100 -1200 -2000]

[ Info:          415.8033456s: 6 minutes, 55 seconds, 803 milliseconds
[ Info:  started timer at: 2025-03-07T19:13:49.583



false


[ Info:  started timer at: 2025-03-07T19:14:40.346


40
k : 20
1
-35998.51981791668
2365.162171449367
40
K : 20
[0 -2000 -100 -1200 -2000]

[ Info:          419.7693508s: 6 minutes, 59 seconds, 769 milliseconds
[ Info:  started timer at: 2025-03-07T19:21:40.125



false


[ Info:  started timer at: 2025-03-07T19:22:30.025


40
k : 20
1
-41944.084170440314
2729.4363854709654
40
K : 20
[0 -2800 -100 -1200 -2000]


[ Info:          419.1910249s: 6 minutes, 59 seconds, 191 milliseconds
[ Info:  started timer at: 2025-03-07T19:29:29.227


false


[ Info:  started timer at: 2025-03-07T19:30:18.763


40
k : 20
1
-46292.85455619754
2826.234564572129


[ Info:          416.8679467s: 6 minutes, 56 seconds, 867 milliseconds


In [18]:
df

30×10 DataFrame
 Row │ u     K     n    s        m       f        p        lamb  mean      std ⋯
     │ Any   Any   Any  Any      Any     Any      Any      Any   Any       Any ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 40.0  20.0  0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -46292.9  282 ⋯
   2 │ 40.0  20.0  0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -41944.1  272
   3 │ 40.0  20.0  0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -35998.5  236
   4 │ 40.0  16.0  0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -46520.9  287
   5 │ 40.0  16.0  0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -42014.8  268 ⋯
   6 │ 40.0  16.0  0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -36032.8  235
   7 │ 40.0  12.0  0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -46874.2  290
   8 │ 40.0  12.0  0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -42161.6  271
   9 │ 40.0  12.0  0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -36063.9  236 ⋯
  10 │ 40.0  8.0   0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -47662.2  303
  11 │ 40.0  8.0   0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -42572.2  274
  ⋮  │  ⋮     ⋮     ⋮      ⋮       ⋮        ⋮        ⋮      ⋮       ⋮          ⋱
  21 │ 30.0  8.0   0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -30769.5  223
  22 │ 30.0  4.0   0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -43952.8  337 ⋯
  23 │ 30.0  4.0   0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -38282.9  292
  24 │ 30.0  4.0   0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -31723.5  243
  25 │ 20.0  8.0   0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -28376.6  244
  26 │ 20.0  8.0   0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -25170.0  216 ⋯
  27 │ 20.0  8.0   0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -21259.3  195
  28 │ 20.0  4.0   0.0  -2800.0  -100.0  -1200.0  -2000.0  1.0   -31381.2  291
  29 │ 20.0  4.0   0.0  -2000.0  -100.0  -1200.0  -2000.0  1.0   -27007.9  251
  30 │ 20.0  4.0   0.0  -1200.0  -100.0  -1200.0  -2000.0  1.0   -22148.7  211 ⋯
                                                     1 column and 9 rows omitted

In [19]:
using CSV
CSV.write("Hetero CW-MDP.csv", df)

"Hetero CW-MDP.csv"