In [2]:
# import Pkg; Pkg.add("POMDPPolicies")
# Pkg.add("POMDPModelTools")
# Pkg.add("Distributions")
# Pkg.add("Combinatorics")
# Pkg.add("StaticArrays")
# Pkg.add("FileIO")
# Pkg.add("JLD2")
# Pkg.add("TickTock")
# Pkg.add("POMDPTools")
# Pkg.add("D3Trees")
# Pkg.add("Random")
# Pkg.add("DataFrames")
# Pkg.add("CSV")

In [3]:
using POMDPs, POMDPTools, QuickPOMDPs, MCTS, DiscreteValueIteration, POMDPSimulators, POMDPModels, POMDPPolicies
using Distributions, Combinatorics, StaticArrays, D3Trees, Random
using FileIO, JLD2, TickTock

In [4]:
Number_level = 4;


gamma=0.95
Transition_matrix = [
    0.8571 0.1429 0.0    0.0;
    0.0    0.8571 0.1429 0.0;
    0.0    0.0    0.8    0.2;
    0.0    0.0    0.0    1.0
]
Observation_matrix=[
    0.8 0.2 0.0 0.0;
    0.1 0.8 0.1 0.0;
    0.0 0.2 0.8 0.0;
    0.0 0.0 0.0 1.0
]
# Observation_matrix=[
#     0.65  0.25 0.1   0.0;
#     0.175 0.65 0.175 0.0;
#     0.1   0.25 0.65  0.0;
#     0.0   0.0  0.0   1.0
# ]

States=Array((1:Number_level))
Observations=Array((1:Number_level))

Initialstates = zeros(Number_level)
Initialstates[1]=1.0
Initialstate = SparseCat(States, Initialstates)

# Initialobss = zeros(Number_level)
# Initialobss[1]=1.0
# Initialobs = SparseCat(States, Initialobss)
Initialobs = SparseCat(Observations, Observation_matrix[1,:])

               SparseCat distribution           
     ┌                                        ┐ 
   1 ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 0.8   
   2 ┤■■■■■■■■■ 0.2                             
   3 ┤ 0.0                                      
   4 ┤ 0.0                                      
     └                                        ┘ 

In [5]:
NumberUnits=20
limit=12
failure_penalty = -1200.0;
maintenance_penalty = -100.0;
setup_cost = -300.0;
normal_operation = 0.0;
system_penalty=-2000

-2000

## Observation function

In [6]:
function observation_function(s)
    return SparseCat(Observations, Observation_matrix[s,:])
end
# obs_std=[1,1.2,1.5]
# obs_mean=[0.5,1,1.5]

# function observation_function(s)
#     if s==Number_level
#         return Deterministic(Number_level)
#     else
#         cont_dist=Normal(obs_mean[s],obs_std[s])
#         probs=zeros(Number_level)
#         for i in 1:(Number_level-1)
#             if i==1
#                 probs[i]=cdf(cont_dist,0.75)
#             elseif i==(Number_level-1)
#                 probs[i]=1-cdf(cont_dist,1.25)
#             else
#                 probs[i]=cdf(cont_dist,i+0.25)-cdf(cont_dist,i-0.25)
#             end
#         end
#         probs ./= sum(probs)
#         return SparseCat(1:(Number_level),probs)
#     end
# end


observation_function (generic function with 1 method)

## Belief updater

In [7]:
function update_belief(b,s_b,a,o) 
    # NOTE: 
    # in input, b is belief from last epoch (before a)
    # a is the last action we took
    # o is the new observation after a
    updated_belief = zeros(Number_level)
    if o==Number_level
        updated_belief[Number_level]=1.0
        return updated_belief
    end
    
    if s_b >= a
    # We assume perfect maintenance and it is know to decision maker(belief updater)
        for sp in 1: Number_level
            #p_obs=pdf(SparseCat(Observations, Observation_matrix[sp,:]),o)
            p_obs=pdf(observation_function(sp),o)
            p_trans = pdf(SparseCat(States,Transition_matrix[1,:]),sp) 
            updated_belief[sp] = p_obs * p_trans
        end
        updated_belief ./= sum(updated_belief)
        return updated_belief
    end
    
    for sp in 1:Number_level
        #p_obs=pdf(SparseCat(Observations, Observation_matrix[sp,:]),o)
        p_obs=pdf(observation_function(sp),o)
        p_trans = 0.0
        for s in 1:Number_level
            p_trans += pdf(SparseCat(States,Transition_matrix[s,:]),sp) * b[s]
        end
        updated_belief[sp] = p_obs * p_trans
    end
        # Normalize the updated belief state to ensure it sums up to 1
        updated_belief ./= sum(updated_belief)
    return updated_belief
end

update_belief (generic function with 1 method)

In [8]:
NumberUnits = 10
belief = [[0.8, 0.2, 0.0, 0.0] for j in 1:NumberUnits]
b = belief[1,:]

1-element Vector{Vector{Float64}}:
 [0.8, 0.2, 0.0, 0.0]

In [9]:
b = belief[1]

4-element Vector{Float64}:
 0.8
 0.2
 0.0
 0.0

In [10]:
p_trans = 0.0
s = 1
sp = 2

p_trans += pdf(SparseCat(States,Transition_matrix[s,:]),sp) * b[s]

0.11432

## Define POMDP

In [11]:
# s is the system-level state vector
#s,r,o,true_a=approximate(s,s_belief,local_a,234) 
# Approximating the solution by taking the state of highest belief as the true state
function approximate(s,s_belief,a,rng=234)
    r=0.0
    prevent_repair= false
    failed_components=count(x->x==Number_level,s_belief)
    if failed_components >= limit
        r += system_penalty
        # if a==Number_level +1
        #     a = Number_level
        # end
    end

    for i in 1:NumberUnits
        if s_belief[i] >= a 
            # Maintenance action is decided based on belief, not true state
            # since we don't know true states when making decision
            if s_belief[i] == Number_level
                r += failure_penalty
                if prevent_repair == false
                    r += setup_cost
                    prevent_repair = true
                end
            else
                r += maintenance_penalty
                if prevent_repair == false
                    r += setup_cost
                    prevent_repair = true
                end
            end
            s[i]=rand(crd[1])
            r += normal_operation
        else
            s[i] = rand(crd[s[i]])
            r = r+normal_operation
        end
    end

    obs=repeat(1:1,NumberUnits)
    for i in 1:NumberUnits
        #obs_distribution = SparseCat(Observations, Observation_matrix[s[i],:])
        obs_distribution = observation_function(s[i])
        obs[i] = rand(obs_distribution)
    end

    return (s=s,r=r,o=obs,a=a)
end

approximate (generic function with 2 methods)

In [12]:
# # Generate random positive numbers and normalize each row
# function generate_prob_matrix(rows, cols)
#     # Create random positive numbers
#     matrix = rand(rows, cols)
    
#     # Normalize each row to sum to 1
#     normalized = matrix ./ sum(matrix, dims=2)
    
#     return normalized
# end

# # Generate 20x4 matrix
# prob_matrix = generate_prob_matrix(20, 4)

In [13]:
# global initialb= zeros(20, 4)  
# global initialb[:, 1] .= 1.0
# s_belief = [argmax(row) for row in eachrow(initialb)]

In [14]:
# belief[1,:]=[0.3,0.3,0.4,0]
# true_a=3
# o[1]=2

In [15]:
# update_belief([0.3,0.3,0.4,0], 3,3, 1)

In [16]:
function findnN()
    println("Finding best nN policy...")
    rewards_nN = zeros(Number_level,Number_level);
    rewards_nN = rewards_nN.+(-100000000.0);
    temp_rewards = zeros(repetition,1);
    # global rewards_nN_std = zeros(Number_level,Number_level);
    # global rewards_nN_std = rewards_nN_std.+(-100000000.0);
    for N in 2:(Number_level)
        for n in 1:N
            # temp_rewards = zeros(repetition,1)
            Threads.@threads  for j in 1:repetition
            #for j in 1:repetition
                s=repeat(1:1,NumberUnits)
                # o=s 
                o = rand(Initialobs, NumberUnits)
                # belief = [[1.0, 0.0, 0.0, 0.0] for j in 1:NumberUnits]
                belief = [Observation_matrix[1,:] for j in 1:NumberUnits]
                R_sequence=[]
                for k in 1:simsteps
                    # s_belief = [argmax(row) for row in eachrow(belief)]
                    s_belief = argmax.(belief)
                    local_a = Number_level +1; # when local_a = 0, no repair unless system fails
                    for i in 1:NumberUnits
                    # if there is any unit reaching or exceeding threshold N, 
                    # maintain all the units reaching or exceeding threshold n.
                        
                        if s_belief[i]>= N
                            local_a=n
                        end
                    end
                    true_a=local_a
                    # s is the system-level state vector
                    s,r,o,true_a=approximate(s,s_belief,local_a,234) 
                    for i in 1: NumberUnits
                        belief[i]=update_belief(belief[i], s_belief[i],true_a, o[i])
                    end
                    append!(R_sequence,r)
                end
                R_discounted=0
                for k in 1:simsteps
                    R_discounted=gamma * R_discounted+R_sequence[simsteps-k+1]
                end
                temp_rewards[j]=R_discounted
            end
            rewards_nN[n,N] = mean(temp_rewards)
            #rewards_nN_std[n,N] = std(temp_rewards)
        end
    end
    # This max_reward is actually wrong in POMDP
    # The (n, N) obtained should be calculated based on true state
    (max_reward,nN)=findmax(rewards_nN)
    
    #println("Max rewards of (n, N)-policy is", max_reward, "n is ", nN[1], "N is ", nN[2])
    #return max_reward, rewards_nN_std[nN], nN
    return nN
end

findnN (generic function with 1 method)

In [17]:
# function generative(s,s_belief,a,rng=234)
#     r=0.0
#     prevent_repair= false
#     failed_components=count(x->x==Number_level,s_belief)
#     if failed_components >= limit
#         r += system_penalty
#         if a==Number_level +1
#             a = Number_level
#         end
#     end

#     for i in 1:NumberUnits
#         if s_belief[i] >= a
#             if s[i] == Number_level
#                 r += failure_penalty
#                 if prevent_repair == false
#                     r += setup_cost
#                     prevent_repair = true
#                 end
#             else
#                 r += maintenance_penalty
#                 if prevent_repair == false
#                     r += setup_cost
#                     prevent_repair = true
#                 end
#             end
#             s[i]=rand(crd[1])
#             r += normal_operation
#         else
#             s[i] = rand(crd[s[i]])
#             r = r+normal_operation
#         end
#     end

#     obs=repeat(1:1,NumberUnits)
#     for i in 1:NumberUnits
#         #obs_distribution = SparseCat(Observations, Observation_matrix[s[i],:])
#         obs_distribution = observation_function(s[i])
#         obs[i] = rand(obs_distribution)
#     end

#     return (s=s,r=r,o=obs,a=a)
# end

In [18]:
function generative(s,s_belief,a,rng=234)
    r=0.0
    # prevent_repair= false
    # failed_components=count(x->x==Number_level,s_belief)
    # if failed_components >= limit
    #     #r += system_penalty
    #     if a==Number_level +1
    #         a = Number_level
    #     end
    # end

    if a <= Number_level
         r += setup_cost
    end

    true_failed_components=count(x->x==Number_level,s)
    if true_failed_components >= limit
        r += system_penalty
    end

    for i in 1:NumberUnits
        if s_belief[i] >= a
            if s[i] == Number_level
                r += failure_penalty
            else
                r += maintenance_penalty
            end
            s[i]=rand(crd[1])
            r += normal_operation
        else
            s[i] = rand(crd[s[i]])
            r = r+normal_operation
        end
    end

    obs=repeat(1:1,NumberUnits)
    for i in 1:NumberUnits
        #obs_distribution = SparseCat(Observations, Observation_matrix[s[i],:])
        obs_distribution = observation_function(s[i])
        obs[i] = rand(obs_distribution)
    end

    return (s=s,r=r,o=obs)
end

generative (generic function with 2 methods)

In [19]:
using DataFrames
df= DataFrame(u=[],K=[],n=[],s=[],m=[],f=[],p=[],mean=[],std=[],nN=[])

cost=[ 
    [0	-800	-100	-1200 -2000],
    [0	-1200	-100	-1200 -2000],
    [0	-1600	-100	-1200 -2000],
    [0	-2000	-100	-1200 -2000],
    [0  -2400   -100    -1200 -2000],
    [0  -2800   -100    -1200 -2000],
    [0  -3200   -100    -1200 -2000]
] 


for units in [20, 25, 30, 40, 50, 60]

    for K in 2:2:convert(Int64, floor((units+1)/2)) 
        
        global NumberUnits=convert(Int64,units)
        global limit=convert(Int64,K)
        global crd = Array{Categorical}(undef,Number_level)
        for i in 1:Number_level
            global crd[i] = Categorical(Transition_matrix[i,:]);
        end
            
        # global initialb= zeros(NumberUnits, Number_level)  
        # global initialb[:, 1] .= 1.0
        for c in cost
            tick()
            println(units)  
            print("K : ")
            println(K)
            global normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty=c
            println(c)  
            global NumberUnits=units

            global simsteps = 100;
            global repetition = 10000;
            global rewards_nN = zeros(Number_level,Number_level);
            global rewards_nN = rewards_nN.+(-100000000.0);
            global rewards_nN_std = zeros(Number_level,Number_level);
            global rewards_nN_std = rewards_nN_std.+(-100000000.0);

            global discount_factor =gamma
            global temp_rewards = zeros(repetition,1);
            # Looking for optimal (n, N)
            nN =findnN()
            n=nN[1]
            N=nN[2]
            
            trials=10000;
            results=zeros(trials)*0.1
            # cnt_maintenance = zeros(trials)
            rewards=0.0
            rewards_std=0.0
            Threads.@threads for h in 1:trials
                s=repeat(1:1,NumberUnits)
                # o=s 
                o = rand(Initialobs, NumberUnits)
                # belief = [[1.0, 0.0, 0.0, 0.0] for j in 1:NumberUnits]
                belief = [Observation_matrix[1,:] for j in 1:NumberUnits]
                R_sequence=[]
              
                
                # maintenance_count = 0
                for k in 1:simsteps
                    # s_belief = [argmax(row) for row in eachrow(belief)]
                    s_belief = argmax.(belief)
                    # if h==1
                    #     println("The belief vector is ", belief)
                    #     println("====================================================")
                    #     println("The maximum likelihood state vector is", s_belief)
                    # end
                    local_a = Number_level +1; 
                    for i in 1:NumberUnits
                    # If there is any unit reaching or exceeding threshold N, 
                    # maintain all the units reaching or exceeding threshold n,
                    # otherwise, no maintenance.
                    # As a result, when system fails, there are components at failure level,
                    # so N must be reached.
                        if s_belief[i]>= N
                            local_a=n
                        end
                    end
                    # true_a=local_a
                    # s is the system-level state vector
                    # if local_a <= Number_level
                    #     # println("maintain")
                    #     maintenance_count += 1
                    # end
                    s,r,o=generative(s,s_belief,local_a,234) 
                    for i in 1: NumberUnits
                        # modified: belief[i,:] to belief[i]
                        belief[i]=update_belief(belief[i], s_belief[i],local_a, o[i])

                    end
                    append!(R_sequence,r)
                end
                R_discounted=0.0
                for k in 1:simsteps
                    R_discounted=gamma * R_discounted+R_sequence[simsteps-k+1]
                end
                # cnt_maintenance[h]=maintenance_count
                results[h]=R_discounted
            end
            rewards=mean(results)
            rewards_std=std(results)
            # N_maintenance = mean(cnt_maintenance)
            println("Rewards of (n, N)-policy is", rewards, "n is ", nN[1], "N is ", nN[2])
            # println("Number of maintenance times is ", N_maintenance)
            pushfirst!(df,[units,limit,normal_operation,setup_cost,maintenance_penalty,failure_penalty,system_penalty,rewards,rewards_std,nN])
        end
    end
end

20
K : 2


[ Info:  started timer at: 2025-03-05T16:20:55.970


[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-11391.02628593657n is 2N is 4
20
K : 2
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T16:31:43.526


Rewards of (n, N)-policy is-12640.356296794056n is 2N is 4
20
K : 2
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T16:41:54.227


Rewards of (n, N)-policy is-13922.700747910812n is 2N is 4
20
K : 2
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T16:52:10.474


Rewards of (n, N)-policy is-15211.44478338024n is 2N is 4
20
K : 2
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T17:02:25.862


Rewards of (n, N)-policy is-16430.37080283853n is 2N is 4
20
K : 2
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T17:12:52.206


Rewards of (n, N)-policy is-17734.239407883928n is 2N is 4
20
K : 2
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T17:23:13.144


Rewards of (n, N)-policy is-18966.01586721733n is 2N is 4
20
K : 4
[0 -800 -100 -1200 -2000]
Finding best nN policy...

[ Info:  started timer at: 2025-03-05T17:33:41.081



Rewards of (n, N)-policy is-10214.197727842491n is 2N is 4
20
K : 4
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T17:44:03.949


Rewards of (n, N)-policy is-11481.621373113157n is 2N is 4
20
K : 4
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T17:54:21.984


Rewards of (n, N)-policy is-12732.468751546363n is 2N is 4
20
K : 4
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T18:04:46.504


Rewards of (n, N)-policy is-14013.604314199081n is 2N is 4
20
K : 4
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T18:15:06.796


Rewards of (n, N)-policy is-15282.472663851226n is 2N is 4
20
K : 4
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T18:25:25.588


Rewards of (n, N)-policy is-16552.781384913294n is 2N is 4
20
K : 4
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T18:35:43.865


Rewards of (n, N)-policy is-17759.26649776334n is 2N is 4
20
K : 6
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T18:46:04.204


Rewards of (n, N)-policy is-10191.427800718424n is 2N is 4
20
K : 6
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T18:56:21.914


Rewards of (n, N)-policy is-11438.206507612029n is 2N is 4
20
K : 6
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T19:06:37.759


Rewards of (n, N)-policy is-12731.151402972699n is 2N is 4
20
K : 6
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T19:16:55.380


Rewards of (n, N)-policy is-13969.448163188841n is 2N is 4
20
K : 6


[ Info:  started timer at: 2025-03-05T19:27:13.120


[0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-15223.257416460881n is 2N is 4
20
K : 6
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T19:37:38.334


Rewards of (n, N)-policy is-16512.47640179382n is 2N is 4
20
K : 6
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T19:47:58.742


Rewards of (n, N)-policy is-17804.786961492504n is 2N is 4
20
K : 

[ Info:  started timer at: 2025-03-05T19:58:21.460


8
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-10177.306315146598n is 2N is 4
20

[ Info:  started timer at: 2025-03-05T20:08:38.645



K : 8
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-11477.300882037296n is 2N is 4
20
K : 8
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T20:18:55.854


Rewards of (n, N)-policy is-12688.516651515962n is 2N is 4
20

[ Info:  started timer at: 2025-03-05T20:29:14.024



K : 8
[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-13979.767447862196n is 2N is 4
20
K : 8
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T20:39:28.622


Rewards of (n, N)-policy is-15300.830813718494n is 2N is 4
20
K : 8
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T20:49:47.631


Rewards of (n, N)-policy is-16523.833603176754n is 2N is 4
20
K : 8
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T21:00:09.822


Rewards of (n, N)-policy is-17806.008016144388n is 2N is 4
20
K : 10
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T21:10:25.359


Rewards of (n, N)-policy is-10189.211255898801n is 2N is 4
20
K : 10
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T21:20:48.163


Rewards of (n, N)-policy is-11435.722057493376n is 2N is 4
20
K : 10
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T21:31:02.178


Rewards of (n, N)-policy is-12712.070486446684n is 2N is 4
20
K : 10
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T21:41:39.693


Rewards of (n, N)-policy is-13949.091933840115n is 2N is 4
20
K : 

[ Info:  started timer at: 2025-03-05T21:52:01.662


10
[0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-15256.506039585987n is 2N is 4
20
K : 10
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T22:02:22.431


Rewards of (n, N)-policy is-16490.542943888147n is 2N is 4
20
K : 10
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T22:12:49.421


Rewards of (n, N)-policy is-17743.488838909365n is 2N is 4
25
K : 2
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T22:23:08.164


Rewards of (n, N)-policy is-13401.877546558391n is 2N is 4
25
K : 2
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T22:35:56.725


Rewards of (n, N)-policy is-14745.460218640133n is 2N is 4
25
K : 2
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T22:48:49.202


Rewards of (n, N)-policy is-16093.469619084211n is 2N is 4
25
K : 2
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T23:01:39.786


Rewards of (n, N)-policy is-17505.892063290554n is 2N is 4
25
K : 2
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T23:14:22.462


Rewards of (n, N)-policy is-18861.00617341573n is 2N is 4
25
K : 2
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T23:27:13.559


Rewards of (n, N)-policy is-20146.352034016574n is 2N is 4
25
K : 2
[0

[ Info:  started timer at: 2025-03-05T23:40:04.449


 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-21598.422889598394n is 2N is 4
25
K : 4
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-05T23:52:53.298


Rewards of (n, N)-policy is-11949.065066204721n is 2N is 4
25
K : 4
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T00:05:40.319


Rewards of (n, N)-policy is-13327.422260148454n is 2N is 4


[ Info:  started timer at: 2025-03-06T00:18:39.739


25
K : 4
[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-14656.734190461018n is 2N is 4
25
K : 4
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T00:31:37.315


Rewards of (n, N)-policy is-16026.070938866927n is 2N is 4
25
K : 4
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T00:44:27.234


Rewards of (n, N)-policy is-17448.516102491885n is 2N is 4
25
K : 4
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T00:57:12.142


Rewards of (n, N)-policy is-18785.54700131134n is 2N is 4
25
K : 4
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T01:09:58.970


Rewards of (n, N)-policy is-20142.682016897605n is 2N is 4
25
K : 6
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T01:22:40.820


Rewards of (n, N)-policy is-11897.423148992939n is 2N is 4
25

[ Info:  started timer at: 2025-03-06T01:35:24.935



K : 6
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-13270.814652660107n is 2N is 4
25
K : 6
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T01:48:12.369


Rewards of (n, N)-policy is-14626.975336875057n is 2N is 4
25
K : 6
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T02:01:01.257


Rewards of (n, N)-policy is-16016.278636334097n is 2N is 4
25
K : 6
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T02:13:45.641


Rewards of (n, N)-policy is-17410.284291608532n is 2N is 4
25
K : 6
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T02:26:33.836


Rewards of (n, N)-policy is-18745.43229321163n is 2N is 4
25
K : 6
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T02:39:29.322


Rewards of (n, N)-policy is-20100.089778147398n is 2N is 4
25
K : 8
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T02:52:21.717


Rewards of (n, N)-policy is-11894.340139949983n is 2N is 4
25
K : 8
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T03:05:04.356


Rewards of (n, N)-policy is-13292.05998484873n is 2N is 4
25
K : 8
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T03:17:51.844


Rewards of (n, N)-policy is-14628.841533313049n is 2N is 4
25
K : 8
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T03:30:40.686


Rewards of (n, N)-policy is-16025.169449591594n is 2N is 4
25
K : 8
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T03:43:29.498


Rewards of (n, N)-policy is-17353.1071172944n is 2N is 4


[ Info:  started timer at: 2025-03-06T03:56:12.191


25
K : 8
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-18784.481708243617n is 2N is 4
25
K : 8
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T04:09:05.120


Rewards of (n, N)-policy is-20123.050056374348n is 2N is 4
25
K : 10
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T04:22:02.704


Rewards of (n, N)-policy is-11894.464781212278n is 2N is 4
25
K : 10
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T04:34:41.775


Rewards of (n, N)-policy is-13266.686447074571n is 2N is 4
25
K : 10
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T04:47:28.324


Rewards of (n, N)-policy is-14623.526900580704n is 2N is 4
25
K : 10
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T05:00:11.491


Rewards of (n, N)-policy is-16023.069430492473n is 2N is 4


[ Info:  started timer at: 2025-03-06T05:12:46.844


25
K : 10
[0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-17329.420194154383n is 2N is 4
25

[ Info:  started timer at: 2025-03-06T05:25:29.182



K : 10
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-18727.156454850632n is 2N is 4
25
K : 10
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T05:38:10.712


Rewards of (n, N)-policy is-20112.308352464737n is 2N is 4
25
K : 12
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T05:50:48.558


Rewards of (n, N)-policy is-11894.350151801133n is 2N is 4
25
K : 12
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T06:03:41.265


Rewards of (n, N)-policy is-13266.442114760086n is 2N is 4
25
K : 12
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T06:16:25.231


Rewards of (n, N)-policy is-14630.737085181376n is 2N is 4
25
K : 12
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T06:29:04.357


Rewards of (n, N)-policy is-16003.119118897694n is 2N is 4
25
K : 12
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T06:41:47.950


Rewards of (n, N)-policy is-17374.747519287015n is 2N is 4
25
K : 12
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T06:54:29.704


Rewards of (n, N)-policy is-18774.298522325505n is 2N is 4
25
K : 12
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T07:07:08.272


Rewards of (n, N)-policy is-20133.357278139978n is 2N is 4
30
K : 2
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T07:19:48.781


Rewards of (n, N)-policy is-15203.762140060104n is 2N is 4
30
K : 2
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T07:34:47.123


Rewards of (n, N)-policy is-16689.52352196983n is 2N is 4
30
K : 2
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T07:49:48.738


Rewards of (n, N)-policy is-18114.097723636816n is 2N is 4


[ Info:  started timer at: 2025-03-06T08:05:12.376


30
K : 2
[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19628.618773329043n is 2N is 4
30
K : 2
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T08:20:24.265


Rewards of (n, N)-policy is-21073.17740517275n is 2N is 4
30
K : 2
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T08:35:27.081


Rewards of (n, N)-policy is-22561.788797462465n is 2N is 4


[ Info:  started timer at: 2025-03-06T08:50:27.106


30
K : 2
[0 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-24025.207960024123n is 2N is 4
30
K : 4
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T09:05:44.920


Rewards of (n, N)-policy is-13620.116688877637n is 2N is 4
30
K : 4
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T09:20:50.504


Rewards of (n, N)-policy is-15082.587686897987n is 2N is 4
30
K : 4
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T09:35:54.080


Rewards of (n, N)-policy is-16529.706685669895n is 2N is 4
30
K : 4
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T09:50:57.835


Rewards of (n, N)-policy is-18012.782259873726n is 2N is 4
30

[ Info:  started timer at: 2025-03-06T10:06:12.542



K : 4
[0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19457.594192419558n is 2N is 4
30
K : 4
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T10:21:15.009


Rewards of (n, N)-policy is-20928.44100689472n is 2N is 4
30
K : 4
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T10:36:36.793


Rewards of (n, N)-policy is-22367.9238779109n is 2N is 4
30
K : 6
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T10:51:45.225


Rewards of (n, N)-policy is-13541.601142699197n is 2N is 4
30
K : 6
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T11:06:52.264


Rewards of (n, N)-policy is-15029.351447584284n is 2N is 4
30
K : 6
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T11:21:52.198


Rewards of (n, N)-policy is-16436.472731272148n is 2N is 4
30
K : 6
[0

[ Info:  started timer at: 2025-03-06T11:36:52.551


 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-17902.459704577952n is 2N is 4
30
K : 6
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T11:51:53.091


Rewards of (n, N)-policy is-19369.34449308098n is 2N is 4


[ Info:  started timer at: 2025-03-06T12:06:56.357


30
K : 6
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-20856.239410851536n is 2N is 4
30
K : 6
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T12:21:56.735


Rewards of (n, N)-policy is-22323.576479314623n is 2N is 4
30
K : 8
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T12:37:04.193


Rewards of (n, N)-policy is-13536.15123721643n is 2N is 4


[ Info:  started timer at: 2025-03-06T12:52:09.083


30
K : 8
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-15018.068992344633n is 2N is 4
30
K : 8
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T13:07:24.065


Rewards of (n, N)-policy is-16467.370037632616n is 2N is 4
30
K : 8
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T13:22:31.392


Rewards of (n, N)-policy is-17935.248619904305n is 2N is 4
30
K : 8
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T13:37:32.862


Rewards of (n, N)-policy is-19401.004506976515n is 2N is 4
30
K : 8
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T13:52:33.139


Rewards of (n, N)-policy is-20824.496235804283n is 2N is 4
30
K : 8
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T14:07:39.916


Rewards of (n, N)-policy is-22339.440149524646n is 2N is 4
30
K : 

[ Info:  started timer at: 2025-03-06T14:22:51.274


10
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-13550.916198670497n is 2N is 4
30
K : 

[ Info:  started timer at: 2025-03-06T14:38:02.156


10
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-15054.77065538954n is 2N is 4
30
K : 10
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T14:53:07.688


Rewards of (n, N)-policy is-16461.534544978702n is 2N is 4
30
K : 10
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T15:08:12.293


Rewards of (n, N)-policy is-17943.287082527655n is 2N is 4
30
K : 10
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T15:23:28.275


Rewards of (n, N)-policy is-19361.719770399326n is 2N is 4
30
K : 10
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T15:38:41.853


Rewards of (n, N)-policy is-20852.222293008555n is 2N is 4
30
K : 10
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T15:53:50.885


Rewards of (n, N)-policy is-22313.85471329366n is 2N is 4
30
K : 12
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T16:09:08.764


Rewards of (n, N)-policy is-13555.822294541424n is 2N is 4
30
K : 12
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T16:24:24.656


Rewards of (n, N)-policy is-15012.72391386726n is 2N is 4
30
K : 12
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T16:39:40.794


Rewards of (n, N)-policy is-16473.83016888566n is 2N is 4
30
K : 12
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T16:54:56.244


Rewards of (n, N)-policy is-17936.146809412345n is 2N is 4
30
K : 12
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T17:10:05.758


Rewards of (n, N)-policy is-19405.416388645524n is 2N is 4
30
K : 12
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T17:25:20.030


Rewards of (n, N)-policy is-20841.14721019297n is 2N is 4
30
K : 12
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T17:40:30.747


Rewards of (n, N)-policy is-22311.680852994406n is 2N is 4
30
K : 14
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T17:55:36.435


Rewards of (n, N)-policy is-13552.178495081871n is 2N is 4
30
K : 14
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T18:10:49.130


Rewards of (n, N)-policy is-15018.001287125311n is 2N is 4
30
K : 14
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T18:25:59.341


Rewards of (n, N)-policy is-16448.956710411774n is 2N is 4
30
K : 14
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T18:41:13.167


Rewards of (n, N)-policy is-17935.607843814803n is 2N is 4
30
K : 14
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T18:56:27.550


Rewards of (n, N)-policy is-19419.483783566382n is 2N is 4


[ Info:  started timer at: 2025-03-06T19:11:43.651


30
K : 14
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-20839.1955795384n is 2N is 4
30
K : 14
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T19:27:00.662


Rewards of (n, N)-policy is-22268.10246002454n is 2N is 4
40
K : 2
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T19:42:17.860


Rewards of (n, N)-policy is-18883.24679684925n is 2N is 4
40
K : 2
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T20:02:30.211


Rewards of (n, N)-policy is-20497.245670888973n is 2N is 4
40
K : 2
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T20:22:50.592


Rewards of (n, N)-policy is-22070.000595096553n is 2N is 4
40
K : 2
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T20:42:59.301


Rewards of (n, N)-policy is-23652.05240784568n is 2N is 4
40
K : 2
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T21:03:05.114


Rewards of (n, N)-policy is-25305.009409462975n is 2N is 4
40
K : 2
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T21:23:07.635


Rewards of (n, N)-policy is-26968.860000187684n is 2N is 4
40
K : 2
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T21:43:15.323


Rewards of (n, N)-policy is-28543.115687126083n is 2N is 4


[ Info:  started timer at: 2025-03-06T22:03:20.918


40
K : 4
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-16803.778476259646n is 2N is 4
40
K : 4


[ Info:  started timer at: 2025-03-06T22:23:32.716


[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-18463.006219403695n is 2N is 4
40
K : 4
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T22:43:53.883


Rewards of (n, N)-policy is-20062.362383070173n is 2N is 4


[ Info:  started timer at: 2025-03-06T23:03:58.561


40
K : 4
[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-21660.396295893275n is 2N is 4
40
K : 4
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T23:24:00.797


Rewards of (n, N)-policy is-23232.668813835575n is 2N is 4
40
K : 4
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-06T23:44:34.140


Rewards of (n, N)-policy is-24898.743881264574n is 2N is 4
40
K : 4
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T00:05:09.932


Rewards of (n, N)-policy is-26533.600746383745n is 2N is 4


[ Info:  started timer at: 2025-03-07T00:25:29.580


40
K : 6
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-16733.16723465701n is 2N is 4


[ Info:  started timer at: 2025-03-07T00:45:47.033


40
K : 6
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-18315.061324464634n is 2N is 4
40
K : 6
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T01:05:57.848


Rewards of (n, N)-policy is-19981.06103608397n is 2N is 4


[ Info:  started timer at: 2025-03-07T01:26:19.928


40
K : 6
[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-21562.770304956437n is 2N is 4
40
K : 6
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T01:46:32.014


Rewards of (n, N)-policy is-23162.058965441967n is 2N is 4
40
K : 6
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T02:06:50.122


Rewards of (n, N)-policy is-24829.30372541491n is 2N is 4
40
K : 6
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T02:27:05.455


Rewards of (n, N)-policy is-26366.30083978644n is 2N is 4
40
K : 8
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T02:47:26.874


Rewards of (n, N)-policy is-16724.89863121428n is 2N is 4
40
K : 8
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T03:07:44.549


Rewards of (n, N)-policy is-18361.50604620493n is 2N is 4


[ Info:  started timer at: 2025-03-07T03:28:01.563


40
K : 8
[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19967.82225956323n is 2N is 4
40
K : 8
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T03:48:12.007


Rewards of (n, N)-policy is-21594.414345719222n is 2N is 4
40
K : 8
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T04:08:33.589


Rewards of (n, N)-policy is-23176.46285475681n is 2N is 4
40
K : 8
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T04:28:43.989


Rewards of (n, N)-policy is-24783.027486675852n is 2N is 4
40
K : 8
[0 -3200 -100 -1200

[ Info:  started timer at: 2025-03-07T04:49:14.409


 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26377.992172943028n is 2N is 4
40
K : 10
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T05:09:38.010


Rewards of (n, N)-policy is-16747.381826910518n is 2N is 4
40
K : 10
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T05:29:54.295


Rewards of (n, N)-policy is-18357.423561881107n is 2N is 4
40
K : 10
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T05:50:15.107


Rewards of (n, N)-policy is-19909.751186866048n is 2N is 4
40
K : 10
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T06:10:37.428


Rewards of (n, N)-policy is-21575.16724044742n is 2N is 4
40
K : 10
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T06:30:42.866


Rewards of (n, N)-policy is-23212.44631494832n is 2N is 4
40
K : 10
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T06:51:04.913


Rewards of (n, N)-policy is-24770.23965247657n is 2N is 4
40
K : 10
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T07:11:23.392


Rewards of (n, N)-policy is-26372.782661815516n is 2N is 4
40
K : 12
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T07:31:36.224


Rewards of (n, N)-policy is-16737.92284765135n is 2N is 4
40
K : 12
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T07:52:00.827


Rewards of (n, N)-policy is-18302.825553949602n is 2N is 4
40
K : 12
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T08:12:37.911


Rewards of (n, N)-policy is-19960.382735311712n is 2N is 4
40
K : 12
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T08:32:48.643


Rewards of (n, N)-policy is-21599.035163820423n is 2N is 4
40
K : 12
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T08:52:57.002


Rewards of (n, N)-policy is-23170.32370484078n is 2N is 4
40
K : 12
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T09:13:14.362


Rewards of (n, N)-policy is-24783.83143282898n is 2N is 4
40

[ Info:  started timer at: 2025-03-07T09:33:26.755



K : 12
[0 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26418.376434795977n is 2N is 4
40
K : 14
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T09:53:38.492


Rewards of (n, N)-policy is-16736.860735010017n is 2N is 4
40
K : 14
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T10:13:55.166


Rewards of (n, N)-policy is-18322.977666231458n is 2N is 4


[ Info:  started timer at: 2025-03-07T10:34:09.487


40
K : 14
[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19985.96124142439n is 2N is 4
40
K : 14
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T10:54:21.494


Rewards of (n, N)-policy is-21589.292211871543n is 2N is 4
40
K : 14
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T11:14:33.690


Rewards of (n, N)-policy is-23145.703888991862n is 2N is 4
40
K : 14
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T11:34:50.320


Rewards of (n, N)-policy is-24807.570268478114n is 2N is 4
40
K : 14
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T11:55:13.268


Rewards of (n, N)-policy is-26399.793558146863n is 2N is 4
40
K : 16
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T12:15:43.396


Rewards of (n, N)-policy is-16747.43944881816n is 2N is 4
40
K : 16
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T12:35:59.297


Rewards of (n, N)-policy is-18327.7581136475n is 2N is 4
40
K : 16
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T12:56:10.757


Rewards of (n, N)-policy is-19974.349192364763n is 2N is 4
40
K : 16
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T13:16:36.725


Rewards of (n, N)-policy is-21549.75537444459n is 2N is 4
40
K : 16
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T13:37:08.250


Rewards of (n, N)-policy is-23157.717111688144n is 2N is 4


[ Info:  started timer at: 2025-03-07T13:57:18.883


40
K : 16
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-24757.961270852895n is 2N is 4
40
K : 16
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T14:17:48.145


Rewards of (n, N)-policy is-26398.729530362587n is 2N is 4
40
K : 18
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T14:38:08.196


Rewards of (n, N)-policy is-16705.908169948692n is 2N is 4


[ Info:  started timer at: 2025-03-07T14:58:23.090


40
K : 18
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-18307.169651788776n is 2N is 4
40
K : 18
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T15:18:54.983


Rewards of (n, N)-policy is-19980.031973072746n is 2N is 4
40
K : 18
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T15:39:19.091


Rewards of (n, N)-policy is-21569.843927547452n is 2N is 4
40
K : 18
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T16:00:06.828


Rewards of (n, N)-policy is-23168.416803972195n is 2N is 4
40
K : 18
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T16:33:47.786


Rewards of (n, N)-policy is-24795.231045900488n is 2N is 4
40
K : 18
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T17:05:35.469


Rewards of (n, N)-policy is-26408.618653046153n is 2N is 4
40
K : 20
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T17:37:33.478


Rewards of (n, N)-policy is-16744.234334322875n is 2N is 4
40
K : 20
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T18:09:22.382


Rewards of (n, N)-policy is-18372.612319318818n is 2N is 4
40
K : 20
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T18:41:17.079


Rewards of (n, N)-policy is-19980.333053824143n is 2N is 4
40
K : 20
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T19:13:10.066


Rewards of (n, N)-policy is-21554.680037382233n is 2N is 4
40
K : 20
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T19:42:08.705


Rewards of (n, N)-policy is-23146.870293393033n is 2N is 4
40
K : 20
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T20:02:31.620


Rewards of (n, N)-policy is-24815.958743034666n is 2N is 4
40
K : 20
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T20:22:39.591


Rewards of (n, N)-policy is-26375.22853350762n is 2N is 4


[ Info:  started timer at: 2025-03-07T20:43:04.459


50
K : 2
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-22302.14338496697n is 2N is 4
50

[ Info:  started timer at: 2025-03-07T21:08:19.235



K : 2
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-24074.31779128671n is 2N is 4
50
K : 2
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T21:34:15.829


Rewards of (n, N)-policy is-25750.205808239138n is 2N is 4
50
K : 2
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T21:59:26.663


Rewards of (n, N)-policy is-27494.85019449154n is 2N is 4
50
K : 2
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T22:24:44.958


Rewards of (n, N)-policy is-29210.34900934912n is 2N is 4
50
K : 2
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T22:50:29.694


Rewards of (n, N)-policy is-31045.20811147138n is 2N is 4
50
K : 2
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-07T23:26:44.010


Rewards of (n, N)-policy is-32735.410529419452n is 2N is 4
50
K : 4
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T00:05:01.102


Rewards of (n, N)-policy is-19966.68116373162n is 2N is 4
50
K : 4
[0 

[ Info:  started timer at: 2025-03-08T00:43:23.868


-1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-21718.80895917966n is 2N is 4
50
K : 4
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T01:21:38.219


Rewards of (n, N)-policy is-23456.436882220438n is 2N is 4
50
K : 4
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T01:52:01.456


Rewards of (n, N)-policy is-25168.18301611427n is 2N is 4
50
K : 4
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T02:18:16.705


Rewards of (n, N)-policy is-26932.618385872698n is 2N is 4
50
K : 4
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T02:43:36.319


Rewards of (n, N)-policy is-28641.22804604464n is 2N is 4
50
K : 4
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T03:09:04.836


Rewards of (n, N)-policy is-30363.73579623439n is 2N is 4
50
K : 6
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T03:34:37.927


Rewards of (n, N)-policy is-19805.388862197724n is 2N is 4
50
K : 6
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T04:00:19.222


Rewards of (n, N)-policy is-21596.375671221598n is 2N is 4
50
K : 6


[ Info:  started timer at: 2025-03-08T04:25:42.683


[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-23277.96037202743n is 2N is 4
50
K : 6
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T04:51:21.825


Rewards of (n, N)-policy is-25024.675263635574n is 2N is 4
50
K : 6
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T05:16:51.597


Rewards of (n, N)-policy is-26788.70974413049n is 2N is 4
50
K : 6
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T05:42:20.084


Rewards of (n, N)-policy is-28500.98364262271n is 2N is 4
50
K : 6
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T06:07:43.938


Rewards of (n, N)-policy is-30235.206760108445n is 2N is 4
50

[ Info:  started timer at: 2025-03-08T06:33:01.556



K : 8
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19794.81854658546n is 2N is 4
50
K : 8
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T06:58:21.003


Rewards of (n, N)-policy is-21595.06454319352n is 2N is 4
50
K : 8
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T07:23:49.570


Rewards of (n, N)-policy is-23276.801151321746n is 2N is 4
50
K : 8
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T07:49:11.782


Rewards of (n, N)-policy is-25007.98779551163n is 2N is 4
50
K : 8
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T08:14:53.355


Rewards of (n, N)-policy is-26825.8679572063n is 2N is 4
50
K : 8
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T08:40:25.627


Rewards of (n, N)-policy is-28524.31367946447n is 2N is 4
50


[ Info:  started timer at: 2025-03-08T09:05:54.959


K : 8
[0 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-30196.19707359929n is 2N is 4


[ Info:  started timer at: 2025-03-08T09:31:39.671


50
K : 10
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19786.643565529354n is 2N is 4
50
K : 10
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T09:57:03.046


Rewards of (n, N)-policy is-21545.47622705179n is 2N is 4
50
K : 10
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T10:22:40.430


Rewards of (n, N)-policy is-23292.5885663524n is 2N is 4
50
K : 10
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T10:48:15.606


Rewards of (n, N)-policy is-24993.32531633823n is 2N is 4
50
K : 10
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T11:13:42.488


Rewards of (n, N)-policy is-26755.58948942161n is 2N is 4
50
K : 10
[0 -2800 -100 -1200 -2000

[ Info:  started timer at: 2025-03-08T11:39:04.529


]
Finding best nN policy...
Rewards of (n, N)-policy is-28445.03236483747n is 2N is 4
50
K : 10
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T12:04:33.801


Rewards of (n, N)-policy is-30225.378851121844n is 2N is 4
50

[ Info:  started timer at: 2025-03-08T12:30:02.705



K : 12
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19786.800003794284n is 2N is 4
50
K : 12
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T12:55:38.164


Rewards of (n, N)-policy is-21542.221952466625n is 2N is 4
50
K : 12
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T13:21:17.731


Rewards of (n, N)-policy is-23314.423055580228n is 2N is 4
50
K : 12
[0

[ Info:  started timer at: 2025-03-08T13:46:51.363


 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-25046.94437013987n is 2N is 4
50
K : 12
[0 

[ Info:  started timer at: 2025-03-08T14:12:27.665


-2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26715.250140004973n is 2N is 4
50
K : 12
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T14:38:11.801


Rewards of (n, N)-policy is-28517.162889623756n is 2N is 4
50
K : 12
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T15:03:52.118


Rewards of (n, N)-policy is-30192.221076933027n is 2N is 4
50
K : 14
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T15:29:23.099


Rewards of (n, N)-policy is-19828.480860449195n is 2N is 4
50
K : 14
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T15:54:51.022


Rewards of (n, N)-policy is-21512.01746640825n is 2N is 4
50
K : 14
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T16:20:37.647


Rewards of (n, N)-policy is-23286.29960825362n is 2N is 4
50
K : 14
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T16:56:55.766


Rewards of (n, N)-policy is-25016.64449089774n is 2N is 4


[ Info:  started timer at: 2025-03-08T17:35:18.353


50
K : 14
[0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26753.422724995176n is 2N is 4


[ Info:  started timer at: 2025-03-08T18:13:41.339


50
K : 14
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-28485.39069417438n is 2N is 4
50
K : 14
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T18:52:06.446


Rewards of (n, N)-policy is-30201.32798481921n is 2N is 4
50
K : 16
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T19:30:30.723


Rewards of (n, N)-policy is-19826.497954686023n is 2N is 4
50

[ Info:  started timer at: 2025-03-08T20:08:48.281



K : 16
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-21567.424619256468n is 2N is 4
50
K : 16
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T20:47:14.431


Rewards of (n, N)-policy is-23275.82726139442n is 2N is 4
50
K : 16
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T21:25:44.332


Rewards of (n, N)-policy is-25029.942692084347n is 2N is 4
50
K : 16
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T22:04:05.190


Rewards of (n, N)-policy is-26743.57327452686n is 2N is 4
50
K : 16
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T22:42:32.803


Rewards of (n, N)-policy is-28506.464455299927n is 2N is 4
50
K : 16
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T23:21:08.457


Rewards of (n, N)-policy is-30205.717130338337n is 2N is 4
50
K : 18
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-08T23:59:29.755


Rewards of (n, N)-policy is-19834.89774485545n is 2N is 4
50
K : 18
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T00:37:55.622


Rewards of (n, N)-policy is-21561.86770801627n is 2N is 4
50
K : 18
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T01:16:15.073


Rewards of (n, N)-policy is-23275.311108254802n is 2N is 4
50
K : 18
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T01:54:28.751


Rewards of (n, N)-policy is-25031.6959828543n is 2N is 4
50
K : 18
[0 -2400 -100

[ Info:  started timer at: 2025-03-09T03:32:49.910


 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26796.284982979072n is 2N is 4
50
K : 18
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T04:11:06.049


Rewards of (n, N)-policy is-28483.587282410568n is 2N is 4
50
K : 18
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T04:49:25.984


Rewards of (n, N)-policy is-30205.83520010418n is 2N is 4
50
K : 20
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T05:27:48.526


Rewards of (n, N)-policy is-19824.34911892209n is 2N is 4
50
K : 20
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T06:06:10.897


Rewards of (n, N)-policy is-21548.506780171556n is 2N is 4
50
K : 20
[

[ Info:  started timer at: 2025-03-09T06:44:24.948


0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-23299.92809495906n is 2N is 4
50
K : 20
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T07:22:45.651


Rewards of (n, N)-policy is-25039.01147667138n is 2N is 4


[ Info:  started timer at: 2025-03-09T08:00:55.646


50
K : 20
[0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26749.10132902251n is 2N is 4


[ Info:  started timer at: 2025-03-09T08:39:30.326


50
K : 20
[0 -2800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-28497.535206992965n is 2N is 4
50
K : 20
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T09:18:02.416


Rewards of (n, N)-policy is-30254.698264021434n is 2N is 4
50
K : 22
[

[ Info:  started timer at: 2025-03-09T09:56:35.947


0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-19809.434110457114n is 2N is 4
50
K : 22
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T10:34:59.204


Rewards of (n, N)-policy is-21561.40930429632n is 2N is 4
50
K : 22

[ Info:  started timer at: 2025-03-09T11:13:21.363



[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-23293.636566297162n is 2N is 4
50
K : 22
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T11:51:49.475


Rewards of (n, N)-policy is-25016.631384070366n is 2N is 4
50
K : 22
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T12:30:07.745


Rewards of (n, N)-policy is-26752.202353436638n is 2N is 4
50
K : 22
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T13:08:43.526


Rewards of (n, N)-policy is-28470.513752893883n is 2N is 4
50

[ Info:  started timer at: 2025-03-09T13:47:09.998



K : 22
[0 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-30199.739109913742n is 2N is 4
50
K : 24
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T14:25:23.978


Rewards of (n, N)-policy is-19822.518119386925n is 2N is 4
50
K : 24
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T15:03:56.247


Rewards of (n, N)-policy is-21526.077965398847n is 2N is 4
50
K : 24
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T15:42:12.045


Rewards of (n, N)-policy is-23297.96568767488n is 2N is 4
50
K : 24
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T16:20:20.499


Rewards of (n, N)-policy is-25047.522466487448n is 2N is 4
50
K : 24
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T16:58:36.741


Rewards of (n, N)-policy is-26724.976956407736n is 2N is 4
50
K : 24
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T17:36:55.305


Rewards of (n, N)-policy is-28489.80957218269n is 2N is 4
50

[ Info:  started timer at: 2025-03-09T18:15:23.691



K : 24
[0 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-30249.978400661636n is 2N is 4
60
K : 2
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T18:53:49.137


Rewards of (n, N)-policy is-25654.923186329917n is 2N is 4
60
K : 2
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T19:39:42.278


Rewards of (n, N)-policy is-27536.1197158604n is 2N is 4
60

[ Info:  started timer at: 2025-03-09T20:25:20.707



K : 2
[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-29323.716758017636n is 2N is 4
60
K : 2


[ Info:  started timer at: 2025-03-09T21:11:02.283


[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-31198.879814679767n is 2N is 4
60
K : 2
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T21:56:50.965


Rewards of (n, N)-policy is-32994.74385460703n is 2N is 4
60
K : 2
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T22:42:42.603


Rewards of (n, N)-policy is-34906.88345996641n is 2N is 4
60
K : 2
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-09T23:28:34.321


Rewards of (n, N)-policy is-36661.159274643884n is 2N is 4
60
K : 4
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T00:14:37.978


Rewards of (n, N)-policy is-23087.240368570543n is 2N is 4
60
K : 4
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T01:00:29.146


Rewards of (n, N)-policy is-24902.698828525317n is 2N is 4
60
K : 4
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T01:46:24.796


Rewards of (n, N)-policy is-26723.898903677367n is 2N is 4
60


[ Info:  started timer at: 2025-03-10T02:32:11.675


K : 4
[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-28543.90423168618n is 2N is 4
60
K : 4
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T03:17:56.560


Rewards of (n, N)-policy is-30447.559858462788n is 2N is 4
60
K : 4
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T04:03:53.131


Rewards of (n, N)-policy is-32217.221032031226n is 2N is 4
60
K : 4
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T04:49:31.037


Rewards of (n, N)-policy is-34096.72060056436n is 2N is 4
60
K : 6
[0 

[ Info:  started timer at: 2025-03-10T05:35:15.021


-800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-22827.572658052955n is 2N is 4
60
K : 6
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T06:20:54.509


Rewards of (n, N)-policy is-24697.43972513789n is 2N is 4
60
K : 6
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T07:06:27.552


Rewards of (n, N)-policy is-26589.403759550063n is 2N is 4
60
K : 6
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T07:52:03.930


Rewards of (n, N)-policy is-28364.404853271808n is 2N is 4
60
K : 6
[

[ Info:  started timer at: 2025-03-10T08:37:43.749


0 -2400 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-30181.074228606616n is 2N is 4
60
K : 6
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T09:23:16.679


Rewards of (n, N)-policy is-32024.293477319356n is 2N is 4
60
K : 6
[

[ Info:  started timer at: 2025-03-10T10:08:53.708


0 -3200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-33884.52767547059n is 2N is 4
60
K : 8
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T10:54:27.551


Rewards of (n, N)-policy is-22833.47815356546n is 2N is 4


[ Info:  started timer at: 2025-03-10T11:39:48.513


60
K : 8
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-24641.22721660237n is 2N is 4
60
K : 8
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T12:25:08.370


Rewards of (n, N)-policy is-26514.736956339784n is 2N is 4
60
K : 8
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T13:04:06.510


Rewards of (n, N)-policy is-28353.58708564322n is 2N is 4
60
K : 8
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T13:34:41.399


Rewards of (n, N)-policy is-30204.34015531466n is 2N is 4
60
K : 8
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T14:04:58.896


Rewards of (n, N)-policy is-32011.546357947587n is 2N is 4
60
K : 8
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T14:35:26.475


Rewards of (n, N)-policy is-33848.1493021418n is 2N is 4
60

[ Info:  started timer at: 2025-03-10T15:05:46.748



K : 10
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-22843.819631935516n is 2N is 4
60
K : 10
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T15:36:29.752


Rewards of (n, N)-policy is-24669.64156925989n is 2N is 4
60

[ Info:  started timer at: 2025-03-10T16:06:39.435



K : 10
[0 -1600 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26502.155724069118n is 2N is 4
60
K : 10
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T16:37:15.951


Rewards of (n, N)-policy is-28379.221018976325n is 2N is 4
60
K : 10
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T17:07:42.327


Rewards of (n, N)-policy is-30234.89797961787n is 2N is 4
60
K : 10
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T17:38:23.292


Rewards of (n, N)-policy is-31988.16318533789n is 2N is 4
60
K : 10
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T18:08:46.552


Rewards of (n, N)-policy is-33874.69346674883n is 2N is 4
60
K : 12
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T18:39:34.405


Rewards of (n, N)-policy is-22838.371121880566n is 2N is 4
60
K : 12
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T19:09:59.363


Rewards of (n, N)-policy is-24665.500494095784n is 2N is 4
60
K : 12
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T19:40:33.870


Rewards of (n, N)-policy is-26520.588453410746n is 2N is 4
60
K : 12
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T20:11:06.593


Rewards of (n, N)-policy is-28331.63441318676n is 2N is 4
60
K : 12
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T20:41:30.520


Rewards of (n, N)-policy is-30201.322045082976n is 2N is 4
60
K : 12
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T21:12:11.594


Rewards of (n, N)-policy is-32040.711819956327n is 2N is 4
60
K : 12
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T21:42:39.513


Rewards of (n, N)-policy is-33813.86580844982n is 2N is 4
60
K : 14
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T22:13:01.322


Rewards of (n, N)-policy is-22847.22041306901n is 2N is 4
60
K : 14
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T22:43:36.865


Rewards of (n, N)-policy is-24703.696545527608n is 2N is 4
60
K : 14
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-10T23:14:14.628


Rewards of (n, N)-policy is-26523.041215656038n is 2N is 4
60

[ Info:  started timer at: 2025-03-10T23:44:44.363



K : 14
[0 -2000 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-28344.331908064152n is 2N is 4
60
K : 14
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T00:15:25.644


Rewards of (n, N)-policy is-30185.58762888477n is 2N is 4
60
K : 14
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T00:45:54.073


Rewards of (n, N)-policy is-32024.541786288613n is 2N is 4
60
K : 14
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T01:16:13.885


Rewards of (n, N)-policy is-33860.151564503736n is 2N is 4
60
K : 16
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T01:46:37.765


Rewards of (n, N)-policy is-22869.742149456444n is 2N is 4


[ Info:  started timer at: 2025-03-11T02:17:03.934


60
K : 16
[0 -1200 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-24685.235574602164n is 2N is 4
60
K : 16
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T02:47:35.176


Rewards of (n, N)-policy is-26528.555524694162n is 2N is 4
60
K : 16
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T03:18:01.086


Rewards of (n, N)-policy is-28340.742330566376n is 2N is 4
60
K : 16
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T03:48:12.529


Rewards of (n, N)-policy is-30193.406338042n is 2N is 4
60
K : 16
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T04:19:02.996


Rewards of (n, N)-policy is-32022.748856926042n is 2N is 4
60
K : 16
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T04:49:32.015


Rewards of (n, N)-policy is-33863.823113022634n is 2N is 4
60
K : 18
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T05:20:06.777


Rewards of (n, N)-policy is-22838.48043137803n is 2N is 4
60
K : 18
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T05:50:31.457


Rewards of (n, N)-policy is-24659.872726226225n is 2N is 4
60
K : 18
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T06:21:13.379


Rewards of (n, N)-policy is-26520.68926721462n is 2N is 4
60
K : 18
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T06:51:30.373


Rewards of (n, N)-policy is-28370.182884525286n is 2N is 4
60
K : 18
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T07:22:03.232


Rewards of (n, N)-policy is-30164.979665967672n is 2N is 4
60
K : 18
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T07:52:31.432


Rewards of (n, N)-policy is-32025.78033191936n is 2N is 4
60
K : 18
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T08:23:22.605


Rewards of (n, N)-policy is-33873.12420474241n is 2N is 4
60
K : 20


[ Info:  started timer at: 2025-03-11T08:53:58.025


[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-22816.213211464885n is 2N is 4
60
K : 20
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T09:24:47.587


Rewards of (n, N)-policy is-24706.401831055624n is 2N is 4
60
K : 20
[0 -1600 

[ Info:  started timer at: 2025-03-11T09:55:14.001


-100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-26523.74760622147n is 2N is 4
60
K : 20
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T10:25:57.180


Rewards of (n, N)-policy is-28354.093482235665n is 2N is 4
60
K : 20
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T10:56:31.798


Rewards of (n, N)-policy is-30215.9624327446n is 2N is 4
60
K : 20
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T11:26:59.282


Rewards of (n, N)-policy is-32007.910515111675n is 2N is 4
60
K : 20
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T11:57:36.134


Rewards of (n, N)-policy is-33831.89492521572n is 2N is 4
60
K : 22
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T12:28:00.212


Rewards of (n, N)-policy is-22835.295733205687n is 2N is 4
60
K : 22
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T12:58:21.505


Rewards of (n, N)-policy is-24681.622233928956n is 2N is 4
60
K : 22
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T13:28:50.165


Rewards of (n, N)-policy is-26504.760185360392n is 2N is 4
60
K : 22
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T13:59:13.706


Rewards of (n, N)-policy is-28316.64837776242n is 2N is 4
60
K : 22
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T14:29:42.834


Rewards of (n, N)-policy is-30161.60821341663n is 2N is 4
60
K : 22
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T15:00:09.908


Rewards of (n, N)-policy is-31971.174900201553n is 2N is 4
60
K : 22
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T15:30:37.005


Rewards of (n, N)-policy is-33829.45094387743n is 2N is 4
60
K : 24
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T16:01:15.553


Rewards of (n, N)-policy is-22847.663508694837n is 2N is 4
60
K : 24
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T16:31:48.157


Rewards of (n, N)-policy is-24690.222955458583n is 2N is 4
60
K : 24
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T17:02:16.930


Rewards of (n, N)-policy is-26504.366079611376n is 2N is 4
60
K : 24
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T17:32:57.126


Rewards of (n, N)-policy is-28352.839514879797n is 2N is 4
60
K : 24
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T18:03:19.229


Rewards of (n, N)-policy is-30198.541323914076n is 2N is 4
60
K : 24
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T18:34:03.111


Rewards of (n, N)-policy is-32042.966152807832n is 2N is 4
60
K : 24
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T19:04:23.833


Rewards of (n, N)-policy is-33914.47287770689n is 2N is 4
60
K : 26
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T19:34:47.533


Rewards of (n, N)-policy is-22830.264854995712n is 2N is 4
60
K : 26
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T20:05:25.028


Rewards of (n, N)-policy is-24684.245389326963n is 2N is 4
60
K : 26
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T20:36:02.240


Rewards of (n, N)-policy is-26510.597497248564n is 2N is 4
60
K : 26
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T21:06:24.430


Rewards of (n, N)-policy is-28358.941000840427n is 2N is 4
60
K : 26
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T21:37:09.367


Rewards of (n, N)-policy is-30175.88379887243n is 2N is 4
60
K : 26
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T22:07:48.889


Rewards of (n, N)-policy is-32080.54414948076n is 2N is 4
60
K : 26
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T22:38:21.291


Rewards of (n, N)-policy is-33853.20058333949n is 2N is 4


[ Info:  started timer at: 2025-03-11T23:08:46.517


60
K : 28
[0 -800 -100 -1200 -2000]
Finding best nN policy...
Rewards of (n, N)-policy is-22836.75082561229n is 2N is 4
60
K : 28
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-11T23:39:18.130


Rewards of (n, N)-policy is-24664.534847289317n is 2N is 4
60
K : 28
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T00:09:33.312


Rewards of (n, N)-policy is-26557.433701710266n is 2N is 4
60
K : 28
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T00:40:29.161


Rewards of (n, N)-policy is-28382.345955506386n is 2N is 4
60
K : 28
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T01:11:09.929


Rewards of (n, N)-policy is-30143.18655950061n is 2N is 4
60
K : 28
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T01:41:54.360


Rewards of (n, N)-policy is-32062.099414472566n is 2N is 4
60
K : 28
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T02:12:25.169


Rewards of (n, N)-policy is-33823.553547005555n is 2N is 4
60
K : 30
[0 -800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T02:42:59.654


Rewards of (n, N)-policy is-22884.211235529743n is 2N is 4
60
K : 30
[0 -1200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T03:13:42.737


Rewards of (n, N)-policy is-24724.260679933483n is 2N is 4
60
K : 30
[0 -1600 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T03:44:23.185


Rewards of (n, N)-policy is-26525.35676244955n is 2N is 4
60
K : 30
[0 -2000 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T04:15:12.493


Rewards of (n, N)-policy is-28332.21991155191n is 2N is 4
60
K : 30
[0 -2400 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T04:45:40.835


Rewards of (n, N)-policy is-30200.146179459727n is 2N is 4
60
K : 30
[0 -2800 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T05:16:12.103


Rewards of (n, N)-policy is-32030.43886929825n is 2N is 4
60
K : 30
[0 -3200 -100 -1200 -2000]
Finding best nN policy...


[ Info:  started timer at: 2025-03-12T05:46:47.625


Rewards of (n, N)-policy is-33853.66417469103n is 2N is 4


In [20]:
df

385×10 DataFrame
 Row │ u    K    n    s      m     f      p      mean      std      nN         ⋯
     │ Any  Any  Any  Any    Any   Any    Any    Any       Any      Any        ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 60   30   0    -3200  -100  -1200  -2000  -33853.7  2696.62  CartesianI ⋯
   2 │ 60   30   0    -2800  -100  -1200  -2000  -32030.4  2557.38  CartesianI
   3 │ 60   30   0    -2400  -100  -1200  -2000  -30200.1  2346.64  CartesianI
   4 │ 60   30   0    -2000  -100  -1200  -2000  -28332.2  2197.88  CartesianI
   5 │ 60   30   0    -1600  -100  -1200  -2000  -26525.4  2021.93  CartesianI ⋯
   6 │ 60   30   0    -1200  -100  -1200  -2000  -24724.3  1883.4   CartesianI
   7 │ 60   30   0    -800   -100  -1200  -2000  -22884.2  1722.09  CartesianI
   8 │ 60   28   0    -3200  -100  -1200  -2000  -33823.6  2712.86  CartesianI
   9 │ 60   28   0    -2800  -100  -1200  -2000  -32062.1  2510.06  CartesianI ⋯
  10 │ 60   28   0    -2400  -100  -1200  -2000  -30143.2  2371.46  CartesianI
  11 │ 60   28   0    -2000  -100  -1200  -2000  -28382.3  2172.36  CartesianI
  ⋮  │  ⋮    ⋮    ⋮     ⋮     ⋮      ⋮      ⋮       ⋮         ⋮              ⋮ ⋱
 376 │ 20   4    0    -1600  -100  -1200  -2000  -12732.5  1623.55  CartesianI
 377 │ 20   4    0    -1200  -100  -1200  -2000  -11481.6  1470.74  CartesianI ⋯
 378 │ 20   4    0    -800   -100  -1200  -2000  -10214.2  1302.9   CartesianI
 379 │ 20   2    0    -3200  -100  -1200  -2000  -18966.0  2622.86  CartesianI
 380 │ 20   2    0    -2800  -100  -1200  -2000  -17734.2  2493.17  CartesianI
 381 │ 20   2    0    -2400  -100  -1200  -2000  -16430.4  2325.67  CartesianI ⋯
 382 │ 20   2    0    -2000  -100  -1200  -2000  -15211.4  2172.42  CartesianI
 383 │ 20   2    0    -1600  -100  -1200  -2000  -13922.7  2044.18  CartesianI
 384 │ 20   2    0    -1200  -100  -1200  -2000  -12640.4  1919.07  CartesianI
 385 │ 20   2    0    -800   -100  -1200  -2000  -11391.0  1835.62  CartesianI ⋯
                                                   1 column and 364 rows omitted

In [21]:
using CSV
CSV.write("Homo (n,N).csv", df)

"Homo (n,N).csv"